services:
  businesses-prod:
    container_name: businesses-prod
    image: businesses-prod:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
      target: production
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    ports:
      - '50009:50009'

  businesses-stag:
    container_name: businesses-stag
    image: businesses-stag:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
      target: builder
    env_file:
      - ./.env.staging
    environment:
      - NODE_ENV=staging
    ports:
      - '50010:50010'

  businesses-dev:
    container_name: businesses-dev
    image: businesses-dev:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
      target: builder
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
    ports:
      - '50011:50011'

  businesses-loc:
    container_name: businesses-loc
    image: businesses-loc:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
      target: local
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
    ports:
      - '50011:50011'
    volumes:
      - ../../microservices/businesses:/app/microservices/businesses
      - /app/microservices/businesses/node_modules
    command: ['npm', 'run', 'development']
