services:
  businesses-prod:
    container_name: businesses-prod
    image: businesses-prod:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50009:50009'

  businesses-stag:
    container_name: businesses-stag
    image: businesses-stag:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50010:50010'

  businesses-dev:
    container_name: businesses-dev
    image: businesses-dev:latest
    build:
      context: ../../
      dockerfile: microservices/businesses/Dockerfile
      target: builder
    env_file:
      - ./.env
    ports:
      - '50011:50011'
