services:
  postgres_businesses_prod:
    container_name: postgres_businesses_prod
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    restart: always
    ports:
      - '5435:5432'
    env_file:
      - ./.env
    volumes:
      - ./postgres/postgres_businesses_prod:/var/lib/postgresql/data
    networks:
      - custom_network

  postgres_businesses_stag:
    container_name: postgres_businesses_stag
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    restart: always
    ports:
      - '5436:5432'
    env_file:
      - ./.env
    volumes:
      - ./postgres/postgres_businesses_stag:/var/lib/postgresql/data
    networks:
      - custom_network

  postgres_businesses_dev:
    container_name: postgres_businesses_dev
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    restart: always
    ports:
      - '5437:5432'
    env_file:
      - ./.env
    volumes:
      - ./postgres/postgres_businesses_dev:/var/lib/postgresql/data
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
