apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloabdul-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloabdul-prod
  template:
    metadata:
      labels:
        app: helloabdul-prod
    spec:
      containers:
        - name: helloabdul-prod
          image: 192.168.1.201/helloabdul-prod:latest
          imagePullPolicy: Always
          command: ["npm", "run", "production"]
          ports:
            - containerPort: 3006
          env:
            - name: PORT
              value: "3006"
          volumeMounts:
            - name: logs
              mountPath: /microfrontend/helloabdul/logs
          resources:
            requests:
              cpu: "25m"
              memory: "100Mi"
            limits:
              cpu: "50m"
              memory: "150Mi"
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: helloabdul-prod
spec:
  selector:
    app: helloabdul-prod
  ports:
    - name: helloabdul-http
      protocol: TCP
      port: 3006
      targetPort: 3006