apiVersion: v1
kind: Service
metadata:
  name: businesses-db
spec:
  ports:
    - port: 5432
  selector:
    app: businesses-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: businesses-db
spec:
  serviceName: businesses-db
  replicas: 1
  selector:
    matchLabels:
      app: businesses-db
  template:
    metadata:
      labels:
        app: businesses-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: businesses-db-secret
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: businesses-db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: businesses-db-secret
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi