---
- name: Install MetalLB
  ansible.builtin.shell: |
    kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
  changed_when: false

- name: Wait for MetalLB controller to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: metallb-system
    name: controller
  register: metallb_controller_status
  until: metallb_controller_status.resources[0].status.readyReplicas|default(0) > 0
  retries: 10
  delay: 5