---
- name: Check if minikube is already installed
  become: true
  stat:
    path: /usr/local/bin/minikube
  register: minikube_binary

- name: Download minikube binary if not present
  become: true
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
    force: no
  when: not minikube_binary.stat.exists

- name: Fix permissions of .minikube directory
  become: true
  file:
    path: "/home/{{ USER }}/.minikube"
    state: directory
    recurse: yes
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0755'

- name: Start minikube (one-time init)
  become: false  # important
  shell: |
    minikube start --driver=docker --cpus=4 --memory=6144 --insecure-registry="{{ SERVER_IP }}:5000"
  args:
    creates: "/home/{{ USER }}/.minikube/machines/minikube"
  environment:
    HOME: "/home/{{ USER }}"
    USER: "{{ USER }}"
