version: '3.8'
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf
    # depends_on:
    #   backend_dev:
    #     condition: service_started
    networks:
      - custom_network

networks:
  custom_network:
    external: true
