version: '3.8'
services:
  crm_dev:
    container_name: crm_dev
    build:
      context: .
      dockerfile: ./crm/Dockerfile
      target: development
    env_file:
      - ./crm/.env
    ports:
      - '5173:5173'
    depends_on:
      - postgres_dev
      - backend_dev
    networks:
      - custom_network
