name: 'troophunter_prod'
services:
  # ci:
  #   extends:
  #     file: docker-compose.ci.yml
  #     service: ci_prod

  # pgadmin_prod:
  #   extends:
  #     file: docker-compose.pgadmin.yml
  #     service: pgadmin_prod

  main-prod:
    extends:
      file: ./microservices/main/docker-compose.backend.yml
      service: main-prod

  auth-prod:
    extends:
      file: ./microservices/auth/docker-compose.backend.yml
      service: auth-prod

  countries-prod:
    extends:
      file: ./microservices/countries/docker-compose.backend.yml
      service: countries-prod

  businesses-prod:
    extends:
      file: ./microservices/businesses/docker-compose.backend.yml
      service: businesses-prod

  queues-prod:
    extends:
      file: ./microservices/queues/docker-compose.backend.yml
      service: queues-prod

  users-prod:
    extends:
      file: ./microservices/users/docker-compose.backend.yml
      service: users-prod

  troophunter-landing-prod:
    extends:
      file: ./microfrontend/troophunter-landing/docker-compose.troophunter.yml
      service: troophunter-landing-prod

  # cloudflare-prod:
  #   extends:
  #     file: docker-compose.cloudflare.yml
  #     service: cloudflare-prod

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
