name: 'troophunter_stag'
services:
  # ci:
  #   extends:
  #     file: docker-compose.ci.yml
  #     service: ci_stag

  # pgadmin_stag:
  #   extends:
  #     file: docker-compose.pgadmin.yml
  #     service: pgadmin_stag

  main-stag:
    extends:
      file: ./microservices/main/docker-compose.backend.yml
      service: main-stag

  auth-stag:
    extends:
      file: ./microservices/auth/docker-compose.backend.yml
      service: auth-stag

  countries-stag:
    extends:
      file: ./microservices/countries/docker-compose.backend.yml
      service: countries-stag

  businesses-stag:
    extends:
      file: ./microservices/businesses/docker-compose.backend.yml
      service: businesses-stag

  queues-stag:
    extends:
      file: ./microservices/queues/docker-compose.backend.yml
      service: queues-stag

  users-stag:
    extends:
      file: ./microservices/users/docker-compose.backend.yml
      service: users-stag

  troophunter-landing-prod:
    extends:
      file: ./microfrontend/troophunter-landing/docker-compose.troophunter.yml
      service: troophunter-landing-prod

  # cloudflare-stag:
  #   extends:
  #     file: docker-compose.cloudflare.yml
  #     service: cloudflare-stag

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
