name: 'troophunter_dev'
services:
  # ci:
  #   extends:
  #     file: docker-compose.ci.yml
  #     service: ci_dev

  main-dev:
    extends:
      file: ./microservices/main/docker-compose.backend.yml
      service: main-dev

  auth-dev:
    extends:
      file: ./microservices/auth/docker-compose.backend.yml
      service: auth-dev

  countries-dev:
    extends:
      file: ./microservices/countries/docker-compose.backend.yml
      service: countries-dev

  businesses-dev:
    extends:
      file: ./microservices/businesses/docker-compose.backend.yml
      service: businesses-dev

  queues-dev:
    extends:
      file: ./microservices/queues/docker-compose.backend.yml
      service: queues-dev

  users-dev:
    extends:
      file: ./microservices/users/docker-compose.backend.yml
      service: users-dev

  troophunter-dev:
    extends:
      file: ./microfrontend/troophunter/docker-compose.troophunter.yml
      service: troophunter-dev

  dev8x-dev:
    extends:
      file: ./microfrontend/dev8x/docker-compose.dev8x.yml
      service: dev8x-dev

  helloabdul-dev:
    extends:
      file: ./microfrontend/helloabdul/docker-compose.helloabdul.yml
      service: helloabdul-dev

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
