# version: '3.8'
services:
  postgres_dev:
    extends:
      file: docker-compose.base.yml
      service: postgres_dev

  ci:
    extends:
      file: docker-compose.ci.yml
      service: ci

  nginx_dev:
    extends:
      file: docker-compose.nginx.yml
      service: nginx_dev

  backend_dev:
    extends:
      file: docker-compose.backend.yml
      service: backend_dev

  crm_dev:
    extends:
      file: docker-compose.crm.yml
      service: crm_dev

  # pgadmin_dev:
  #   extends:
  #     file: docker-compose.pgadmin.yml
  #     service: pgadmin_dev

volumes:
  pgadmin-data:
  nginx:

networks:
  custom_network:
    driver: bridge
