version: '3.8'
services:
  ngrok_prod:
    container_name: ngrok_prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./ngrok/Dockerfile
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    ports:
      - '4040:4040'
    env_file:
      - ./ngrok/.env
    volumes:
      - ./ngrok/ngrok.prod.yml:/etc/ngrok.yml
    networks:
      - custom_network

  ngrok_stag:
    container_name: ngrok_stag
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./ngrok/Dockerfile
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    ports:
      - '4041:4040'
    env_file:
      - ./ngrok/.env
    volumes:
      - ./ngrok/ngrok.stag.yml:/etc/ngrok.yml
    networks:
      - custom_network

  ngrok_dev:
    container_name: ngrok_dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./ngrok/Dockerfile
    command:
      - 'start'
      - '--all'
      - '--config'
      - '/etc/ngrok.yml'
    ports:
      - '4042:4040'
    env_file:
      - ./ngrok/.env
    volumes:
      - ./ngrok/ngrok.dev.yml:/etc/ngrok.yml
    networks:
      - custom_network

networks:
  custom_network:
    name: custom_network
    driver: bridge
