name: 'troophunter_stag'
services:
  # ci:
  #   extends:
  #     file: docker-compose.ci.yml
  #     service: ci_stag

  main-stag:
    extends:
      file: ./microservices/main/docker-compose.backend.yml
      service: main-stag

  auth-stag:
    extends:
      file: ./microservices/auth/docker-compose.backend.yml
      service: auth-stag

  countries-stag:
    extends:
      file: ./microservices/countries/docker-compose.backend.yml
      service: countries-stag

  businesses-stag:
    extends:
      file: ./microservices/businesses/docker-compose.backend.yml
      service: businesses-stag

  queues-stag:
    extends:
      file: ./microservices/queues/docker-compose.backend.yml
      service: queues-stag

  users-stag:
    extends:
      file: ./microservices/users/docker-compose.backend.yml
      service: users-stag

  troophunter-stag:
    extends:
      file: ./microfrontend/troophunter/docker-compose.troophunter.yml
      service: troophunter-stag

  dev8x-stag:
    extends:
      file: ./microfrontend/dev8x/docker-compose.dev8x.yml
      service: dev8x-stag

  helloabdul-stag:
    extends:
      file: ./microfrontend/helloabdul/docker-compose.helloabdul.yml
      service: helloabdul-stag

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
