version: '3.8'
services:
  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/backend/entrypoint.sh']
    env_file:
      - ./backend/.env
    ports:
      - '50001:50001'
    depends_on:
      postgres_dev:
        condition: service_started
    networks:
      - custom_network
