# Use the official Node.js 20.5.1 image as the base image
FROM node:20.5.1 as build

# Set the working directory inside the container
WORKDIR /app

# Copy the rest of the project files to the container
COPY . .

# Install project dependencies
RUN npm install

# Change the working directory to app/backend and start the server
WORKDIR /app/backend
CMD ["npm", "run", "dev"]
