services:
  pgadmin_prod:
    container_name: pgadmin_prod
    build:
      context: .
      dockerfile: ./pgadmin/Dockerfile
    ports:
      - '60001:80'
    env_file:
      - ./backend/.env
    volumes:
      - ./pgadmin/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres_prod:
        condition: service_started
    networks:
      - custom_network

  pgadmin_stag:
    container_name: pgadmin_stag
    build:
      context: .
      dockerfile: ./pgadmin/Dockerfile
    ports:
      - '60002:80'
    env_file:
      - ./backend/.env
    volumes:
      - ./pgadmin/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres_stag:
        condition: service_started
    networks:
      - custom_network

  pgadmin_dev:
    container_name: pgadmin_dev
    build:
      context: .
      dockerfile: ./pgadmin/Dockerfile
    ports:
      - '60003:80'
    env_file:
      - ./backend/.env
    volumes:
      - ./pgadmin/pgadmin:/var/lib/pgadmin
    depends_on:
      postgres_dev:
        condition: service_started
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge
