services:
  backend_prod:
    container_name: backend_prod
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/backend/entrypoint.sh']
    env_file:
      - ./backend/.env
    ports:
      - '50001:50001'
    depends_on:
      postgres_prod:
        condition: service_started
    networks:
      - custom_network

  backend_stag:
    container_name: backend_stag
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/backend/entrypoint.sh']
    env_file:
      - ./backend/.env
    ports:
      - '50002:50001'
    depends_on:
      postgres_stag:
        condition: service_started
    networks:
      - custom_network

  backend_dev:
    container_name: backend_dev
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/backend/entrypoint.sh']
    env_file:
      - ./backend/.env
    ports:
      - '50003:50001'
    depends_on:
      postgres_dev:
        condition: service_started
    networks:
      - custom_network
