name: 'troophunter_dev'
services:
  # ci:
  #   extends:
  #     file: docker-compose.ci.yml
  #     service: ci_dev

  # pgadmin_dev:
  #   extends:
  #     file: docker-compose.pgadmin.yml
  #     service: pgadmin_dev

  main-dev:
    extends:
      file: ./microservices/main/docker-compose.backend.yml
      service: main-dev

  auth-dev:
    extends:
      file: ./microservices/auth/docker-compose.backend.yml
      service: auth-dev

  countries-dev:
    extends:
      file: ./microservices/countries/docker-compose.backend.yml
      service: countries-dev

  businesses-dev:
    extends:
      file: ./microservices/businesses/docker-compose.backend.yml
      service: businesses-dev

  queues-dev:
    extends:
      file: ./microservices/queues/docker-compose.backend.yml
      service: queues-dev

  users-dev:
    extends:
      file: ./microservices/users/docker-compose.backend.yml
      service: users-dev

  troophunter-landing-dev:
    extends:
      file: ./microfrontend/troophunter-landing/docker-compose.troophunter.yml
      service: troophunter-landing-dev

  # cloudflare-dev:
  #   extends:
  #     file: docker-compose.cloudflare.yml
  #     service: cloudflare-dev

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
