name: 'helloabdul_dev'
services:
  ansible:
    extends:
      file: docker-compose.ansible.yml
      service: ansible_dev

  ci:
    extends:
      file: docker-compose.ci.yml
      service: ci_dev

  postgres_dev:
    extends:
      file: docker-compose.base.yml
      service: postgres_dev

  # pgadmin_dev:
  #   extends:
  #     file: docker-compose.pgadmin.yml
  #     service: pgadmin_dev

  backend_dev:
    extends:
      file: docker-compose.backend.yml
      service: backend_dev

  crm_dev:
    extends:
      file: docker-compose.crm.yml
      service: crm_dev

  cloudflare_dev:
    extends:
      file: docker-compose.cloudflare.yml
      service: cloudflare_dev

volumes:
  pgadmin-data:

networks:
  custom_network:
    driver: bridge
