version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - '50001:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '50002:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=Ssg123777
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  backend:
    entrypoint: ['/bin/bash', './entrypoint.sh']
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    ports:
      - '50003:50003'
    depends_on:
      - postgres

  crm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: crm
    ports:
      - '50004:50004'

volumes:
  pgadmin-data:
