# Horizontal Pod Autoscaler for main API gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main-prod
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
---
# Vertical Pod Autoscaler for main API gateway
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: main-vpa
  namespace: default
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: main-prod
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledResources: ["memory"]
        controlledValues: "RequestsOnly"
        minAllowed:
          cpu: "100m"
          memory: "128Mi"
        maxAllowed:
          cpu: "500m"
          memory: "768Mi"
---
# Pod Disruption Budget for main API gateway
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: main-pdb
  namespace: default
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: main-prod
