/**
 * ADE — Self-Audit & Proposal Pipeline (E3.3 / M20)
 *
 * Periodic pass over trace and verdict data. Emits three proposal streams:
 * 1. Failure entries (persistent loop failures)
 * 2. Constitution amendments (recurring guardrail violations / misalignments)
 * 3. Frontier cases (successful novel patterns or blind spots)
 *
 * Proposals are emitted as markdown files in `<outDir>/proposals/`
 * for Tier-A batch ratification by a human.
 */

import { existsSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { readTrace } from './trace.js';
import { readVerdicts } from './verdicts.js';
import type { RunRecord, VerdictEntry } from './schema.js';

export function runSelfAudit(outDir: string): void {
  console.log(`\n🔍 Running Self-Audit Pipeline (M20)...`);

  const traces = readTrace(outDir);
  const verdicts = readVerdicts(outDir);

  if (traces.length === 0 && verdicts.length === 0) {
    console.log('⚠ No trace or verdict data found. Audit aborted.');
    return;
  }

  const proposalsDir = join(outDir, 'proposals');
  if (!existsSync(proposalsDir)) {
    mkdirSync(proposalsDir, { recursive: true });
  }

  const { failureProposals, constitutionProposals, evalProposals } = analyzeData(traces, verdicts);

  const failurePath = join(proposalsDir, 'failure-catalogue-proposals.md');
  const constitutionPath = join(proposalsDir, 'constitution-amendment-proposals.md');
  const evalPath = join(proposalsDir, 'frontier-eval-cases.md');

  writeFileSync(failurePath, failureProposals, 'utf-8');
  writeFileSync(constitutionPath, constitutionProposals, 'utf-8');
  writeFileSync(evalPath, evalProposals, 'utf-8');

  console.log(`✅ Audit complete. 3 proposals emitted to ${proposalsDir}`);
}

function analyzeData(traces: RunRecord[], verdicts: VerdictEntry[]) {
  // 1. Cluster recurring hard-gate violations
  const violationCounts: Record<string, { count: number; runs: string[] }> = {};
  for (const t of traces) {
    if (t.hard_violations && t.hard_violations.length > 0) {
      for (const v of t.hard_violations) {
        const clusterKey = v.split(':')[0] || v;
        if (!violationCounts[clusterKey]) {
          violationCounts[clusterKey] = { count: 0, runs: [] };
        }
        violationCounts[clusterKey].count++;
        if (!violationCounts[clusterKey].runs.includes(t.run_id)) {
          violationCounts[clusterKey].runs.push(t.run_id);
        }
      }
    }
  }

  // 2. Critic vs Human Disagreements
  const disagreements = verdicts.filter((v) => v.human_verdict && v.critic_verdict && ((v.human_verdict === 'approve' && v.critic_verdict === 'fail') || (v.human_verdict === 'reject' && v.critic_verdict === 'pass')));

  // 3. Systematically low-scoring briefs
  const lowestScoring = traces
    .filter((t) => t.scores && t.scores.weighted_total < 60)
    .sort((a, b) => a.scores.weighted_total - b.scores.weighted_total)
    .slice(0, 5);

  // Generate Proposals
  let failureProposals = '# Failure Catalogue Proposals\n\nGenerated by M20 Self-Audit.\n\n';
  let hasFailures = false;
  for (const [key, data] of Object.entries(violationCounts)) {
    if (data.count > 1) {
      hasFailures = true;
      failureProposals += `## Recurring Hard-Gate: ${key}\n`;
      failureProposals += `- **Count:** ${data.count} violations\n`;
      failureProposals += `- **Evidence:** Runs ${data.runs.slice(0, 3).join(', ')}${data.runs.length > 3 ? '...' : ''}\n`;
      failureProposals += `- **Proposal:** Add to \`failures/02-implementation.md\` or adjust threshold.\n\n`;
    }
  }

  // Look for runs that failed outright
  const failedRuns = traces.filter((t) => t.verdict === 'fail');
  if (failedRuns.length > 3) {
    hasFailures = true;
    failureProposals += `## Recurring Generation Failures\n`;
    failureProposals += `- **Count:** ${failedRuns.length} overall failed runs\n`;
    failureProposals += `- **Evidence:** Runs ${failedRuns
      .slice(0, 3)
      .map((r) => r.run_id)
      .join(', ')}\n`;
    failureProposals += `- **Proposal:** Inspect generator constraints or Critic threshold.\n\n`;
  }

  if (!hasFailures) failureProposals += '*No recurring hard-gate violations detected.*\n';

  let constitutionProposals = '# Constitution Amendment Proposals\n\nGenerated by M20 Self-Audit.\n\n';
  if (disagreements.length > 0) {
    constitutionProposals += `## Detected Critic↔Human Misalignment\n`;
    constitutionProposals += `Found ${disagreements.length} cases where the Critic and Human disagreed.\n\n`;
    for (const d of disagreements.slice(0, 5)) {
      constitutionProposals += `- **Run ID:** ${d.run_id}\n`;
      constitutionProposals += `  - Human: ${d.human_verdict}\n`;
      constitutionProposals += `  - Critic: ${d.critic_verdict} (Score: ${d.critic_score})\n`;
      if (d.notes) constitutionProposals += `  - Notes: ${d.notes}\n`;
    }
    constitutionProposals += `\n**Proposal:** Review the Design Constitution principles for these cases to better align the Critic with human taste.\n`;
  } else {
    constitutionProposals += '*No significant Critic↔Human disagreements detected.*\n';
  }

  let evalProposals = '# Frontier Eval Cases Proposals\n\nGenerated by M20 Self-Audit.\n\n';

  const strongVerdicts = verdicts.filter((v) => v.rating === 'strong');
  if (strongVerdicts.length > 0) {
    evalProposals += `## Novel High-Quality Patterns\n`;
    evalProposals += `The following cases received a 'strong' human rating.\n\n`;
    for (const v of strongVerdicts.slice(0, 5)) {
      evalProposals += `- **Run ID:** ${v.run_id}\n`;
      evalProposals += `  - Candidate: ${v.candidate_id || v.preferred}\n`;
    }
    evalProposals += `\n**Proposal:** Crystallize these into the Library or benchmark.\n\n`;
  }

  if (lowestScoring.length > 0) {
    evalProposals += `## Low-Scoring Blind Spots\n`;
    evalProposals += `The following cases scored consistently low, indicating potential domain blind spots.\n\n`;
    for (const t of lowestScoring) {
      evalProposals += `- **Run ID:** ${t.run_id}\n`;
      evalProposals += `  - Score: ${t.scores.weighted_total}\n`;
      evalProposals += `  - Critic Feedback: ${t.critic_feedback.slice(0, 100)}...\n`;
    }
    evalProposals += `\n**Proposal:** Add these cases to the frozen benchmark in \`spec/13-evaluation-charter.md\`.\n`;
  } else if (strongVerdicts.length === 0) {
    evalProposals += '*No low-scoring blind spots or novel patterns detected.*\n';
  }

  return { failureProposals, constitutionProposals, evalProposals };
}
