---
- name: Enable Windows Firewall
  win_firewall_profile:
    name: Domain
    state: on

- name: Enable Windows Firewall for Private Profile
  win_firewall_profile:
    name: Private
    state: on

- name: Enable Windows Firewall for Public Profile
  win_firewall_profile:
    name: Public
    state: on

- name: Allow inbound HTTP (port 80)
  win_firewall_rule:
    name: "Allow HTTP"
    localport: 80
    protocol: tcp
    direction: in
    action: allow
    enabled: yes
    profile: any

- name: Allow inbound HTTPS (port 443)
  win_firewall_rule:
    name: "Allow HTTPS"
    localport: 443
    protocol: tcp
    direction: in
    action: allow
    enabled: yes
    profile: any

- name: Allow inbound WinRM (port 5986)
  win_firewall_rule:
    name: "Allow WinRM HTTPS"
    localport: 5986
    protocol: tcp
    direction: in
    action: allow
    enabled: yes
    profile: any
