---
- name: Install iftop
  package:
    name: iftop
    state: present

- name: Install required system packages
  apt:
    pkg:
      - curl
      - vim
      - git
      - ufw
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true