---
- name: Tag and push Docker images to private registry
  shell: |
    docker tag {{ item }}-{{ ENVIRONMENT }}:latest {{ SERVER_IP }}:5000/{{ item }}-{{ ENVIRONMENT }}:latest
    docker push {{ SERVER_IP }}:5000/{{ item }}-{{ ENVIRONMENT }}:latest
  loop:
    - main
    - auth
    - businesses
    - countries
    - queues
    - users
  args:
    executable: /bin/bash
  register: push_output
  ignore_errors: false

- name: Debug output of docker push
  debug:
    var: push_output.results
