---
- name: Enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Allow prod ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 50000
    - 50003
    - 50006
    - 50009
    - 50012
    - 50015
    - 3000    
    - 5175
  when: ENVIRONMENT == "prod"

- name: Allow stag ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 50001
    - 50004
    - 50007
    - 50010
    - 50013
    - 50016
    - 3001    
    - 5175
  when: ENVIRONMENT == "stag"

- name: Allow dev ports
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 50002
    - 50005
    - 50008
    - 50011
    - 50014
    - 50017
    - 3002    
    - 5175
  when: ENVIRONMENT == "dev"