---
- name: Ensure certs directory exists
  file:
    path: "/home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/main/src/certs"
    state: directory
    mode: '0755'

- name: Copy cert files into the certs folder under microservices/main
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item.src }}"
    dest: "/home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/main/src/certs/{{ item.dest }}"
  with_items:
    - { src: "auth/auth-cert.pem", dest: "auth-cert.pem" }
    - { src: "auth/auth-key.pem", dest: "auth-key.pem" }
    - { src: "countries/countries-cert.pem", dest: "countries-cert.pem" }
    - { src: "countries/countries-key.pem", dest: "countries-key.pem" }
    - { src: "states/states-cert.pem", dest: "states-cert.pem" }
    - { src: "states/states-key.pem", dest: "states-key.pem" }
    - { src: "cities/cities-cert.pem", dest: "cities-cert.pem" }
    - { src: "cities/cities-key.pem", dest: "cities-key.pem" }
    - { src: "users/users-cert.pem", dest: "users-cert.pem" }
    - { src: "users/users-key.pem", dest: "users-key.pem" }
    - { src: "businesses/businesses-cert.pem", dest: "businesses-cert.pem" }
    - { src: "businesses/businesses-key.pem", dest: "businesses-key.pem" }
    - { src: "leads/leads-cert.pem", dest: "leads-cert.pem" }
    - { src: "leads/leads-key.pem", dest: "leads-key.pem" }
    - { src: "queues/queues-cert.pem", dest: "queues-cert.pem" }
    - { src: "queues/queues-key.pem", dest: "queues-key.pem" }
    - { src: "city-queues/city-queues-cert.pem", dest: "city-queues-cert.pem" }
    - { src: "city-queues/city-queues-key.pem", dest: "city-queues-key.pem" }
    - { src: "ca/ca-cert.pem", dest: "ca-cert.pem" }

- name: Copy certs file from certs/auth into host microservices/auth.
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item }}"
    dest: "/home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/auth/src/certs/"
  with_items:
    - "auth/auth-cert.pem"
    - "auth/auth-key.pem"
    - "ca/ca-cert.pem"

- name: Copy certs file from certs/countries into host microservices/countries.
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item }}"
    dest: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/countries/src/certs
  with_items:
    - "countries/countries-cert.pem"
    - "countries/countries-key.pem"
    - "ca/ca-cert.pem"

- name: Copy certs file from certs/businesses into host microservices/businesses.
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item }}"
    dest: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/businesses/src/certs
  with_items:
    - "businesses/businesses-cert.pem"
    - "businesses/businesses-key.pem"
    - "ca/ca-cert.pem"

- name: Copy certs file from certs/queues into host microservices/queues.
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item }}"
    dest: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/queues/src/certs
  with_items:
    - "queues/queues-cert.pem"
    - "queues/queues-key.pem"
    - "ca/ca-cert.pem"

- name: Copy certs file from certs/users into host microservices/users.
  copy:
    src: "{{ ENV_PATH }}/certs/{{ item }}"
    dest: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/microservices/users/src/certs
  with_items:
    - "users/users-cert.pem"
    - "users/users-key.pem"
    - "ca/ca-cert.pem"
