---
- name: Stop kubelet service
  service:
    name: kubelet
    state: stopped
    enabled: no
  ignore_errors: true

- name: Remove Kubernetes packages
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: absent
    purge: yes

- name: Unhold kubelet, kubeadm, kubectl (if held)
  shell: |
    apt-mark unhold kubelet kubeadm kubectl
  register: unhold_result
  changed_when: "'kubelet' in unhold_result.stdout or 'kubeadm' in unhold_result.stdout or 'kubectl' in unhold_result.stdout"
  ignore_errors: true

- name: Remove Kubernetes APT repository
  file:
    path: /etc/apt/sources.list.d/kubernetes.list
    state: absent

- name: Clean APT cache
  apt:
    autoclean: yes
    autoremove: yes

- name: Remove kube config directory for user
  file:
    path: /home/{{ ansible_user }}/.kube
    state: absent
  ignore_errors: true

- name: Remove kube config from root
  file:
    path: /root/.kube
    state: absent
  ignore_errors: true

- name: Remove kubelet and kubeadm data directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/kubernetes
    - /var/lib/etcd
    - /var/lib/kubelet
    - /var/lib/cni
    - /opt/cni
    - /etc/cni
  ignore_errors: true

- name: Remove Calico CNI components (if any)
  shell: |
    kubectl delete -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  ignore_errors: true
  become: false
  become_user: "{{ ansible_user }}"

- name: Print cleanup completion message
  debug:
    msg: "Kubernetes components have been completely removed from the system."
