services:
  countries-prod:
    container_name: countries-prod
    image: countries-prod:latest
    build:
      context: ../../
      dockerfile: microservices/countries/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50006:50006'

  countries-stag:
    container_name: countries-stag
    image: countries-stag:latest
    build:
      context: ../../
      dockerfile: microservices/countries/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50007:50007'

  countries-dev:
    container_name: countries-dev
    image: countries-dev:latest
    build:
      context: ../../
      dockerfile: microservices/countries/Dockerfile
      target: builder
    env_file:
      - ./.env
    ports:
      - '50008:50008'
