---
- name: Check if istioctl is already installed
  stat:
    path: /usr/local/bin/istioctl
  register: istioctl_binary

- name: Download istioctl
  get_url:
    url: https://github.com/istio/istio/releases/download/1.22.0/istioctl-1.22.0-linux-amd64.tar.gz
    dest: /tmp/istioctl.tar.gz
    mode: '0644'
  when: not istioctl_binary.stat.exists

- name: Extract istioctl
  unarchive:
    src: /tmp/istioctl.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    extra_opts: [--strip-components=0]
  when: not istioctl_binary.stat.exists

- name: Move istioctl binary
  command: mv /usr/local/bin/istioctl-1.22.0-linux-amd64 /usr/local/bin/istioctl
  args:
    removes: /usr/local/bin/istioctl-1.22.0-linux-amd64
  when: not istioctl_binary.stat.exists

- name: Ensure istioctl is executable
  file:
    path: /usr/local/bin/istioctl
    mode: '0755'

- name: Install Istio on the cluster
  command: istioctl install --set profile=default -y
  environment:
    KUBECONFIG: /home/{{ USER }}/.kube/config

- name: Check if default namespace already labeled
  command: kubectl get namespace default -o jsonpath='{.metadata.labels.istio-injection}'
  environment:
    KUBECONFIG: /home/{{ USER }}/.kube/config
  register: ns_label_check
  failed_when: false
  changed_when: false

- name: Label default namespace for Istio injection
  command: kubectl label namespace default istio-injection=enabled --overwrite
  environment:
    KUBECONFIG: /home/{{ USER }}/.kube/config
  when: ns_label_check.stdout != 'enabled'
