services:
  troophunter-prod:
    container_name: troophunter-prod
    image: troophunter-prod:latest
    build:
      context: ../../
      dockerfile: microfrontend/troophunter/Dockerfile
    env_file:
      - ./.env.production
    ports:
      - '5173:5173'

  troophunter-stag:
    container_name: troophunter-stag
    image: troophunter-stag:latest
    build:
      context: ../../
      dockerfile: microfrontend/troophunter/Dockerfile
    env_file:
      - ./.env.staging
    ports:
      - '5174:5174'

  troophunter-dev:
    container_name: troophunter-dev
    image: troophunter-dev:latest
    build:
      context: ../../
      dockerfile: microfrontend/troophunter/Dockerfile
      target: builder
    env_file:
      - ./.env.development
    ports:
      - '5175:5175'
