---
- name: Ensure the destination directory exists
  file:
    path: "/home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/"
    state: directory
    owner: "{{ USER }}"
    group: "{{ USER }}"
    mode: '0755'

- name: Copy scraper files from scraper into host scraper.
  copy:
    src: "{{ ENV_PATH }}/{{ PROJECT_NAME }}/"
    dest: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/
  become: true

- name: Change ownership of the copied files and directories
  become: true
  become_user: root
  command: chown -R {{ USER }}:{{ USER }} /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/
