QUERIES_CHATGPT = [
    "Accountant",
    "Acupuncture Clinic",
    "Addiction Treatment Center",
    "Adult Day Care Center",
    "Advertising Agency",
    "African Restaurant",
    "Agricultural Service",
    "AIDS Resource Center",
    "Air Conditioning Contractor",
    "Air Duct Cleaning Service",
    "Airline",
    "Airport",
    "Alcoholism Treatment Program",
    "Allergist",
    "Alternative Medicine Practitioner",
    "Ambulance Service",
    "Amusement Center",
    "Amusement Park",
    "Anesthesiologist",
    "Animal Control Service",
    "Animal Hospital",
    "Animal Rescue Service",
    "Animal Shelter",
    "Antique Store",
    "Apartment Building",
    "Appliance Repair Service",
    "Appliance Store",
    "Aquarium",
    "Arabic Restaurant",
    "Architect",
    "Art Gallery",
    "Art Restoration Service",
    "Art School",
    "Art Supply Store",
    "Artificial Plant Supplier",
    "Asian Fusion Restaurant",
    "Assisted Living Facility",
    "Astrologer",
    "Attorney",
    "ATV Dealer",
    "Audiologist",
    "Audio Visual Equipment Rental Service",
    "Audio Visual Equipment Supplier",
    "Auto Auction",
    "Auto Body Parts Supplier",
    "Auto Body Shop",
    "Auto Dent Removal Service",
    "Auto Electrical Service",
    "Auto Glass Shop",
    "Auto Insurance Agency",
    "Auto Machine Shop",
    "Auto Parts Store",
    "Auto Radiator Repair Service",
    "Auto Repair Shop",
    "Auto Spring Shop",
    "Auto Sunroof Shop",
    "Auto Tag Agency",
    "Auto Tune Up Service",
    "Auto Upholsterer",
    "Auto Wrecker",
    "Automated Teller Machine",
    "Automation Consultant",
    "Aviation Consultant",
    "Awning Supplier",
    "Baby Clothing Store",
    "Baby Store",
    "Bagel Shop",
    "Bail Bonds Service",
    "Bait Shop",
    "Baker",
    "Balloon Artist",
    "Balloon Ride Tour Agency",
    "Balloon Store",
    "Band",
    "Band Instrument Repair Service",
    "Bankruptcy Attorney",
    "Bankruptcy Service",
    "Banquet Hall",
    "Bar",
    "Bar & Grill",
    "Barbecue Restaurant",
    "Barber School",
    "Barber Shop",
    "Bartending School",
    "Baseball Club",
    "Baseball Field",
    "Baseball Goods Store",
    "Baseball League",
    "Baseball Stadium",
    "Basement Remodeler",
    "Basketball Club",
    "Basketball Court",
    "Basketball Store",
    "Bathroom Remodeler",
    "Bathtub Refinishing Service",
    "Battery Manufacturer",
    "Battery Store",
    "Beach",
    "Beach Resort",
    "Bead Store",
    "Bead Wholesaler",
    "Bearing Supplier",
    "Beauty Product Supplier",
    "Beauty Products Vending Machine",
    "Beauty Salon",
    "Beauty School",
    "Bed & Breakfast",
    "Bedding Store",
    "Beekeeper",
    "Beer Distributor",
    "Beer Store",
    "Bicycle Rental Service",
    "Bicycle Repair Shop",
    "Bicycle Store",
    "Billiards Supply Store",
    "Bingo Hall",
    "Biofeedback Therapist",
    "Biological Products Supplier",
    "Biotechnology Company",
    "Bird Control Service",
    "Bird Shop",
    "Birth Center",
    "Birth Certificate Service",
    "Bistro",
    "Blacksmith",
    "Blasting Contractor",
    "Blinds Shop",
    "Blood Bank",
    "Blueprint Service",
    "Board Game Club",
    "Boat Accessories Supplier",
    "Boat Club",
    "Boat Cover Supplier",
    "Boat Dealer",
    "Boat Rental Service",
    "Boat Repair Shop",
    "Boat Storage Facility",
    "Boat Tour Agency",
    "Boat Trailer Dealer",
    "Boat Transporter",
    "Boatyard",
    "Body Piercing Shop",
    "Body Shop",
    "Boiler Manufacturer",
    "Boiler Repair Service",
    "Boiler Supplier",
    "Bolt Supplier",
    "Book Publisher",
    "Book Restoration Service",
    "Book Store",
    "Bookbinder",
    "Bookkeeping Service",
    "Bookmaker",
    "Boot Repair Shop",
    "Bottled Water Supplier",
    "Boutique",
    "Bowling Alley",
    "Box Lunch Supplier",
    "Boxing Gym",
    "Boxing Ring",
    "Brake Shop",
    "Brasserie",
    "Brazilian Restaurant",
    "Breakwater Supplier",
    "Brewery",
    "Brewpub",
    "Brick Manufacturer",
    "Brick Repair Service",
    "Bridal Shop",
    "Bridge Club",
    "Bridge Construction Contractor",
    "Bridge Designer",
    "Bridge Inspection Service",
    "Bridge Jumping Location",
    "Bridge Restoration Service",
    "Bridging Loan Provider",
    "Briefing Area",
    "Brightness Testing Service",
    "British Goods Store",
    "British Restaurant",
    "Broadband Service Provider",
    "Broadcasting Equipment Supplier",
    "Brochure Printing Service",
    "Bronze Manufacturer",
    "Bronze Sculpture",
    "Buddhist Temple",
    "Buffet Restaurant",
    "Building Cleaning Service",
    "Building Consultant",
    "Building Contractor",
    "Building Design Company",
    "Building Engineer",
    "Building Equipment Hire Service",
    "Building Inspection Service",
    "Building Maintenance Company",
    "Building Materials Market",
    "Building Materials Store",
    "Building Restoration Service",
    "Building Society",
    "Building Surveyor",
    "Bungee Jumping Center",
    "Bunsik Restaurant",
    "Buoy Supplier",
    "Burial Ground",
    "Burial Service",
    "Bus Charter and Rental Service",
    "Bus Company",
    "Bus Station",
    "Bus Stop",
    "Bus Ticket Agency",
    "Business Administration Service",
    "Business Broker",
    "Business Center",
    "Business Development Service",
    "Business Hotel",
    "Business Management Consultant",
    "Business Park",
    "Business School",
    "Business to Business Service",
    "Butcher Shop",
    "Butchery Equipment Supplier",
    "Button Store",
    "Cabane à Sucre",
    "Cabaret",
    "Cabinet Maker",
    "Cable Car Station",
    "Cable Company",
    "Cable Manufacturer",
    "Cable Stayed Bridge",
    "Cable Supplier",
    "Café",
    "Cajun Restaurant",
    "Cake Decorating Equipment Shop",
    "Cake Shop",
    "Calçot Restaurant",
    "Calderium Supplier",
    "Calendar Printing Service",
    "Call Center",
    "Camcorder Repair Service",
    "Camera Repair Service",
    "Camera Store",
    "Camera Support and Stabilization Service",
    "Campground",
    "Camping Store",
    "Campsite",
    "Canadian Restaurant",
    "Canoe and Kayak Rental Service",
    "Canoe and Kayak Store",
    "Canoeing and Kayaking Spot",
    "Cantonese Restaurant",
    "Cape Malay Restaurant",
    "Capsule Hotel",
    "Car Alarm Supplier",
    "Car Battery Store",
    "Car Dealer",
    "Car Detailing Service",
    "Car Inspection Station",
    "Car Leasing Service",
    "Car Manufacturer",
    "Car Racing Track",
    "Car Rental Agency",
    "Car Repair and Maintenance",
    "Car Stereo Store",
    "Car Wash",
    "Caravan Dealer",
    "Caravan Park",
    "Carbon Supplier",
    "Cardiologist",
    "Cardiology Clinic",
    "Cardiopulmonary Resuscitation Training",
    "Career Guidance Service",
    "Caribbean Restaurant",
    "Caricature Artist",
    "Carnival Supply Store",
    "Carpenter",
    "Carpet Cleaning Service",
    "Carpet Installer",
    "Carpet Store",
    "Carrom Club",
    "Carsharing Service",
    "Cartographic Service",
    "Cartridge Refill Store",
    "Cash and Carry Wholesaler",
    "Cash Register Supplier",
    "Casino",
    "Cassoulet Restaurant",
    "Cast Iron Supplier",
    "Casting Agency",
    "Castle",
    "Casual Dining Restaurant",
    "Catalonian Restaurant",
    "Catalog Showroom",
    "Catered Apartment",
    "Caterer",
    "Catering Food and Drink Supplier",
    "Catholic Church",
    "Cattle Market",
    "Caulking Service",
    "Cave",
    "Ceiling Contractor",
    "Ceiling Fan Store",
    "Celebrity Impersonator",
    "Cell Phone Accessory Store",
    "Cell Phone Repair Service",
    "Cell Phone Store",
    "Cemetery",
    "Central American Restaurant",
    "Central Asian Restaurant",
    "Certified Public Accountant",
    "Certified Translator",
    "Chabad House",
    "Chain Link Fence Contractor",
    "Chalet Rental Agency",
    "Chamber of Commerce",
    "Champagne Bar",
    "Championship Tourist Attraction",
    "Championship Venue",
    "Charcoal Supplier",
    "Charcuterie Restaurant",
    "Charity",
    "Charity Organization",
    "Charity Shop",
    "Cheese Shop",
    "Cheesesteak Restaurant",
    "Chemical Manufacturer",
    "Chemical Plant",
    "Chemical Wholesaler",
    "Chess Club",
    "Chess Instructor",
    "Chevrolet Dealer",
    "Chicken Hatchery",
    "Chicken Restaurant",
    "Chicken Wings Restaurant",
    "Child Psychologist",
    "Childbirth Education Center",
    "Children's Amusement Center",
    "Children's Clothing Store",
    "Children's Club",
    "Children's Entertainer",
    "Children's Furniture Store",
    "Children's Museum",
    "Children's Party Service",
    "Children's Store",
    "Children's Theater",
    "Chilean Restaurant",
    "Chimney Sweep",
    "Chinese Herbal Medicine Store",
    "Chinese Language School",
    "Chinese Medicine Clinic",
    "Chinese Medicine Store",
    "Chinese Restaurant",
    "Chinese Takeout Restaurant",
    "Chiropractor",
    "Chocolate Shop",
    "Christian Book Store",
    "Christian Church",
    "Christian College",
    "Christian High School",
    "Christian Science Church",
    "Christmas Decoration Store",
    "Christmas Market",
    "Christmas Store",
    "Church",
    "Church of Christ",
    "Church of God",
    "Church of Jesus Christ of Latter-day Saints",
    "Church of the Nazarene",
    "Church Supply Store",
    "Cider Mill",
    "City Clerk's Office",
    "City Courthouse",
    "City Government Office",
    "City Hall",
    "City Park",
    "City Tax Office",
    "Civic Center",
    "Civil Defense Agency",
    "Civil Engineer",
    "Civil Engineering Company",
    "Classic Car Dealer",
    "Classic Car Restoration Service",
    "Classical Music Store",
    "Clay Target Shooting Range",
    "Cleaners",
    "Cleaning Service",
    "Climate Control System Supplier",
    "Climbing Gym",
    "Climbing Instructor",
    "Clinic",
    "Clinical Psychologist",
    "Clock Repair Service",
    "Closed Circuit Television Equipment Supplier",
    "Cloth Diaper Service",
    "Clothing Alteration Service",
    "Clothing Store",
    "Clutch Repair Service",
    "Cocktail Bar",
    "Cocktail Ingredients Supplier",
    "Coffee Machine Supplier",
    "Coffee Roasters",
    "Coffee Shop",
    "Coffee Store",
    "Coin Dealer",
    "Coin Operated Laundry Equipment Supplier",
    "Coin Operated Machine Repair Service",
    "Coin Operated Washer and Dryer Supplier",
    "Coin-Operated Carwash",
    "Cold Storage Facility",
    "Collectibles Store",
    "College",
    "College Counseling Service",
    "College Preparatory School",
    "Collision Repair Center",
    "Color Consultant",
    "Comedy Club",
    "Comic Book Store",
    "Commercial Agent",
    "Commercial Artists",
    "Commercial Building Contractor",
    "Commercial Cleaning Service",
    "Commercial Printer",
    "Commercial Real Estate Agency",
    "Commercial Real Estate Inspector",
    "Commercial Real Estate Renting and Leasing",
    "Commercial Refrigeration Equipment Supplier",
    "Commercial Refrigeration Repair Service",
    "Commercial Swimming Pool Service",
    "Commercial Truck Dealer",
    "Commercial Vehicle Dealer",
    "Commercial Vehicle Inspection Station",
    "Commercial Vehicle Rental Agency",
    "Commercial Vehicle Repair Service",
    "Commercial Vehicle Storage Facility",
    "Commodity Exchange",
    "Communication Tower",
    "Community Center",
    "Community College",
    "Community Health Centre",
    "Community Supported Agriculture",
    "Composting Service",
    "Computer Animation Studio",
    "Computer Club",
    "Computer Consultant",
    "Computer Graphics Service",
    "Computer Repair Service",
    "Computer Security Service",
    "Computer Service",
    "Computer Software Store",
    "Computer Store",
    "Computer Support and Services",
    "Computer Training School",
    "Concert Hall",
    "Concrete Contractor",
    "Concrete Cutting Service",
    "Concrete Pumping Service",
    "Condo Complex",
    "Condominium Rental Agency",
    "Confectionery",
    "Conference Center",
    "Consignment Shop",
    "Construction Company",
    "Construction Equipment Supplier",
    "Construction Machine Dealer",
    "Construction Machine Rental Service",
    "Construction Machine Repair Service",
    "Construction Material Supplier",
    "Construction Project Management Consultant",
    "Construction Safety Consultant",
    "Construction Sand and Gravel Supplier",
    "Construction Surveyor",
    "Consulate",
    "Consumer Electronics Repair Service",
    "Consumer Organization",
    "Contact Lens Supplier",
    "Container Supplier",
    "Contemporary Art Museum",
    "Convenience Store",
    "Convention Center",
    "Conveyor Belt Supplier",
    "Cookie Shop",
    "Cooking Class",
    "Cooking School",
    "Copier Repair Service",
    "Copy Shop",
    "Corporate Campus",
    "Corporate Office",
    "Corporate Retreat Center",
    "Cosmetic Dentist",
    "Cosmetic Products Manufacturer",
    "Cosmetics Store",
    "Costume Rental Service",
    "Cottage",
    "Counseling Center",
    "Country Club",
    "County Courthouse",
    "Courier Service",
    "Court Reporter",
    "Courthouse",
    "Crane Dealer",
    "Crane Rental Agency",
    "Crane Service",
    "Credit Counseling Service",
    "Credit Reporting Agency",
    "Cremation Service",
    "Creperie",
    "Cricket Ground",
    "Crisis Center",
    "Crocodile Farm",
    "Cruise Agency",
    "Cruise Line Company",
    "Cruises",
    "Cuban Restaurant",
    "Culinary School",
    "Cultural Center",
    "Cupcake Shop",
    "Currency Exchange Service",
    "Curry Restaurant",
    "Curtain Supplier",
    "Custom Home Builder",
    "Custom Label Printer",
    "Custom T-shirt Store",
    "Customs Broker",
    "Cutlery Store",
    "CV Joint Repair Shop",
    "Cycle Shop",
    "Dairy Farm",
    "Dairy Store",
    "Dance Company",
    "Dance Hall",
    "Dance School",
    "Dance Store",
    "Dancing Supply Store",
    "Danish Restaurant",
    "Data Recovery Service",
    "Day Care Center",
    "Day Spa",
    "Deck Builder",
    "Defense Attorney",
    "Deli",
    "Delivery Restaurant",
    "Demolition Contractor",
    "Dental Clinic",
    "Dental Hygienist",
    "Dental Implants Periodontist",
    "Dental Insurance Agency",
    "Dental Laboratory",
    "Dental School",
    "Dental Supply Store",
    "Dentist",
    "Denture Care Center",
    "Department Store",
    "Dermatologist",
    "Design School",
    "Dessert Restaurant",
    "Diabetes Center",
    "Diagnostic Center",
    "Dialysis Center",
    "Diamond Buyer",
    "Diamond Dealer",
    "Diamond Wholesaler",
    "Diaper Service",
    "Dietitian",
    "Dim Sum Restaurant",
    "Diner",
    "Dinner Theater",
    "Direct Mail Advertising",
    "Disabilities Service",
    "Disabled Sports Center",
    "Disc Golf Course",
    "Disciples of Christ Church",
    "Disco Club",
    "Discount Store",
    "Distillery",
    "Divorce Lawyer",
    "Dj Supply Store",
    "DJ Training School",
    "Dock Builder",
    "Doctor",
    "Dog Breeder",
    "Dog Hostel",
    "Dog Park",
    "Dog Sitter",
    "Dog Trainer",
    "Dog Walker",
    "Doll Restoration Service",
    "Doll Store",
    "Dominican Restaurant",
    "Donations Center",
    "Donut Shop",
    "Door Supplier",
    "Dormitory",
    "Dot Com Agency",
    "Double Glazing Installer",
    "Doughnut Shop",
    "Draperies & Curtains Store",
    "Dress Store",
    "Dressmaker",
    "Drilling Contractor",
    "Drive-In Movie Theater",
    "Drive-Thru Restaurant",
    "Driving Instructor",
    "Driving Range",
    "Drug Addiction Treatment Center",
    "Drug Testing Service",
    "Drum Store",
    "Dry Cleaner",
    "Dry Ice Supplier",
    "Dry Wall Contractor",
    "Dry Wall Supply Store",
    "Duct Cleaning Service",
    "Dump Truck Dealer",
    "Dumpster Rental Service",
    "Dutch Restaurant",
    "DVD Store",
    "Dyslexia Tutoring Service",
    "E-commerce Service",
    "Ear Piercing Service",
    "Early Childhood Education Center",
    "Eastern European Restaurant",
    "Eating Disorder Treatment Center",
    "Eco Tour Agency",
    "Eclectic Restaurant",
    "Economic Development Agency",
    "Ecuadorian Restaurant",
    "Editorial Services",
    "Educational Consultant",
    "Educational Supply Store",
    "Egyptian Restaurant",
    "Electric Motor Repair Shop",
    "Electric Motor Store",
    "Electric Utility Company",
    "Electric Vehicle Charging Station",
    "Electrical Appliance Repair Service",
    "Electrical Installation Service",
    "Electrical Supply Store",
    "Electrolysis Hair Removal Service",
    "Electronic Parts Supplier",
    "Electronics Manufacturer",
    "Electronics Repair Shop",
    "Electronics Store",
    "Elementary School",
    "Elevator Installation & Repair Service",
    "Elevator Manufacturer",
    "Embassy",
    "Embroidery Service",
    "Emergency Care Physician",
    "Emergency Dental Service",
    "Emergency Lighting Equipment Supplier",
    "Emergency Locksmith Service",
    "Emergency Management Agency",
    "Emergency Room",
    "Emergency Training School",
    "Employment Attorney",
    "Employment Center",
    "Employment Consultant",
    "Employment Service",
    "Endocrinologist",
    "Endodontist",
    "Energy Equipment Supplier",
    "Energy Supplier",
    "Engine Rebuilding Service",
    "Engineering Consultant",
    "Engineering School",
    "Engraving Service",
    "Entertainer",
    "Entertainment Agency",
    "Environmental Consultant",
    "Environmental Engineer",
    "Environmental Health Service",
    "Environmental Organization",
    "Equipment Rental Agency",
    "Ergonomics Consultant",
    "Escape Room Center",
    "Escort Service",
    "Estate Appraiser",
    "Estate Liquidator",
    "Estate Planning Attorney",
    "Ethnic Grocery Store",
    "Event Management Company",
    "Event Planner",
    "Event Ticket Seller",
    "Excavating Contractor",
    "Executive Search Firm",
    "Exercise Equipment Store",
    "Exhaust System Shop",
    "Exterminator",
    "Eye Care Center",
    "Eyeglass Repair Service",
    "Eyewear Manufacturer",
    "Fabric Store",
    "Facial Spa",
    "Factory Outlet Store",
    "Family Counselor",
    "Family Law Attorney",
    "Family Planning Center",
    "Family Practice Physician",
    "Farm Equipment Supplier",
    "Farmers' Market",
    "Fashion Accessories Store",
    "Fashion Consultant",
    "Fashion Design School",
    "Fast Food Restaurant",
    "Fence Contractor",
    "Fertility Clinic",
    "Fertilizer Supplier",
    "Fiber Optic Cable Supplier",
    "Fiberglass Repair Service",
    "Figurine Shop",
    "Filipino Restaurant",
    "Film Production Company",
    "Filter Supplier",
    "Financial Planner",
    "Fine Dining Restaurant",
    "Fire Damage Restoration Service",
    "Fire Protection Consultant",
    "Fireplace Store",
    "Firewood Supplier",
    "Fireworks Store",
    "First Aid Kit Supplier",
    "Fish & Chips Restaurant",
    "Fish Farm",
    "Fish Hatchery",
    "Fish Market",
    "Fish Store",
    "Fishing Charter",
    "Fishing Club",
    "Fishing Store",
    "Fitness Center",
    "Fitness Equipment Store",
    "Flag Store",
    "Flea Market",
    "Flight School",
    "Floor Refinishing Service",
    "Floor Sanding and Polishing Service",
    "Flooring Contractor",
    "Flooring Store",
    "Florist",
    "Foam Rubber Supplier",
    "Folk Art Museum",
    "Fondue Restaurant",
    "Food Bank",
    "Food Court",
    "Food Delivery Service",
    "Food Manufacturer",
    "Food Processing Equipment Supplier",
    "Food Products Supplier",
    "Food Stand",
    "Food Tour Agency",
    "Food Truck",
    "Foot Care Clinic",
    "Foot Massage Parlor",
    "Football Club",
    "Foreclosure Service",
    "Forest",
    "Forestry Service",
    "Forklift Dealer",
    "Forklift Rental Service",
    "Formal Wear Store",
    "Fort",
    "Foster Care Service",
    "Foundation",
    "Fountain Contractor",
    "Fountain Repair Service",
    "Fragrance Store",
    "Franchising Service",
    "Free Clinic",
    "Free Parking Area",
    "Freezing Plant",
    "French Restaurant",
    "Fried Chicken Takeaway",
    "Fried Rice Takeaway",
    "Friend of the Court",
    "Frieze Art Fair",
    "Frozen Dessert Equipment Supplier",
    "Frozen Dessert Shop",
    "Frozen Food Manufacturer",
    "Fruit and Vegetable Processing Plant",
    "Fruit and Vegetable Store",
    "Fuel Supplier",
    "Fuel Wholesaler",
    "Fulfillment Center",
    "Full-Service Restaurant",
    "Funeral Home",
    "Fur Coat Shop",
    "Fur Wholesaler",
    "Furniture Maker",
    "Furniture Rental Service",
    "Furniture Repair Shop",
    "Furniture Store",
    "Furniture Wholesaler",
    "Futon Store",
    "Futsal Court",
    "Futsal Field",
    "Futsal Stadium",
    "Gambling Instructor",
    "Gambling Lawyer",
    "Gambling Rehab Center",
    "Game Store",
    "Garage",
    "Garage Builder",
    "Garage Door Supplier",
    "Garage Door Repair Service",
    "Garage Door Supplier",
    "Garage Door Installation Service",
    "Garage Door Opener Supplier",
    "Garage Door Opener Installation Service",
    "Garage Floor Coating Contractor",
    "Garage Organizer",
    "Garage Sale",
    "Garden",
    "Garden Center",
    "Garden Designer",
    "Garden Machinery Supplier",
    "Garden Pond Supplier",
    "Garden Shredder Supplier",
    "Garden Sprinkler System Contractor",
    "Garden Supply Store",
    "Garden Tour Agency",
    "Gardening Club",
    "Gardening Instructor",
    "Gas Company",
    "Gas Cylinder Supplier",
    "Gas Installation Service",
    "Gas Logs Supplier",
    "Gas Station",
    "Gastroenterologist",
    "Gated Community",
    "Gay Bar",
    "Gay Sauna",
    "Gemologist",
    "General Contractor",
    "General Hospital",
    "General Practice Attorney",
    "General Register Office",
    "General Store",
    "Generator Shop",
    "Genetic Counselor",
    "Geriatrician",
    "German Bakery",
    "German Restaurant",
    "Gift Basket Store",
    "Gift Shop",
    "Gingerbread House Supplier",
    "Glass Block Supplier",
    "Glass Blower",
    "Glass Cutting Service",
    "Glass Engraver",
    "Glass Etching Service",
    "Glass Manufacturer",
    "Glass Repair Service",
    "Glass Shop",
    "Glassware Manufacturer",
    "Glassware Store",
    "Glazier",
    "Glider Plane School",
    "Gliding Club",
    "Gluten-Free Bakery",
    "Gluten-Free Restaurant",
    "Gold Dealer",
    "Gold Prospecting Supply Store",
    "Golf Cart Dealer",
    "Golf Course",
    "Golf Course Builder",
    "Golf Driving Range",
    "Golf Equipment Repair Service",
    "Golf Instructor",
    "Golf Resort",
    "Golf Shop",
    "Gondola Ride Service",
    "Government Office",
    "Government Office Equipment Supplier",
    "Government Relations Consultant",
    "Government Trade Commission Office",
    "Grab Hire Service",
    "Grain Elevator",
    "Granite Supplier",
    "Graphic Designer",
    "Graphic Designer Supply Store",
    "Greek Restaurant",
    "Green Grocer",
    "Greenhouse",
    "Greenhouse Builder",
    "Greeting Card Shop",
    "Greyhound Stadium",
    "Grocery Delivery Service",
    "Grocery Store",
    "Groundwater Consultant",
    "Group Accommodation",
    "Group Home",
    "Guard Tour Agency",
    "Guardrail Contractor",
    "Guest House",
    "Guild Hall",
    "Guitar Instructor",
    "Guitar Store",
    "Gun Club",
    "Gun Range",
    "Gun Safety Training Center",
    "Gun Shop",
    "Gunsmith",
    "Gutter Cleaning Service",
    "Gutter Contractor",
    "Gutter Supply Store",
    "Gym",
    "Gymnastics Center",
    "Gyrotonic Studio",
    "Hair Extensions Supplier",
    "Hair Removal Service",
    "Hair Replacement Service",
    "Hair Salon",
    "Hairdresser Supply Store",
    "Haitian Restaurant",
    "Halal Restaurant",
    "Halfway House",
    "Ham Shop",
    "Hamburger Restaurant",
    "Hand Surgeon",
    "Handbag Designer",
    "Handbag Store",
    "Handicapped Transportation Service",
    "Handicraft",
    "Handicraft Exporter",
    "Handicraft Importer",
    "Handicraft Product Manufacturer",
    "Handicraft Store",
    "Handloom",
    "Handmade Furniture Shop",
    "Handmade Home Goods Shop",
    "Handmade Jewelry Shop",
    "Hang Glider Training Center",
    "Hang-Gliding Area",
    "Harbor",
    "Hard Rock Cafe",
    "Hardwood Floor Refinishing Service",
    "Hardwood Flooring Contractor",
    "Hardware Store",
    "Hat Shop",
    "Haunted House",
    "Hawaiian Goods Store",
    "Hawaiian Restaurant",
    "Hay Supplier",
    "Health and Beauty Shop",
    "Health Consultant",
    "Health Food Restaurant",
    "Health Food Store",
    "Health Resort",
    "Hearing Aid Repair Service",
    "Hearing Aid Store",
    "Heart Hospital",
    "Heating Contractor",
    "Heating Equipment Supplier",
    "Heating Oil Supplier",
    "Heating System Repair Service",
    "Heating System Supplier",
    "Heavy Equipment Rental Service",
    "Heavy Equipment Repair Service",
    "Heavy Equipment Supplier",
    "Heavy Hauling Service",
    "Heavy Towing Service",
    "Helicopter Charter Service",
    "Helicopter Tour Agency",
    "Hemp Products Supplier",
    "Herbal Medicine Store",
    "High School",
    "High School Athletic Field",
    "High School Band",
    "High School Basketball Court",
    "High School Football Field",
    "High School Soccer Field",
    "High School Track",
    "High School Volleyball Court",
    "High-Speed Internet Service Provider",
    "Highway Patrol Office",
    "Hindu Temple",
    "Historic Landmark",
    "Historic Preservation Office",
    "Historic Site",
    "Historical Place",
    "Historical Society",
    "Historical Tour Agency",
    "Hobby Store",
    "Hockey Club",
    "Hockey Rink",
    "Hockey Supply Store",
    "Holistic Medicine Practitioner",
    "Home Automation Company",
    "Home Builder",
    "Home Cinema Installer",
    "Home Goods Store",
    "Home Health Care Service",
    "Home Health Care Service Supply Store",
    "Home Improvement Store",
    "Home Inspector",
    "Home Insurance Agency",
    "Home Theater Store",
    "Homebrew Supply Store",
    "Homemade Food Delivery Service",
    "Honda Dealer",
    "Honey Farm",
    "Hookah Bar",
    "Horse Boarding Stable",
    "Horse Breeder",
    "Horse Carriage Ride Service",
    "Horse Riding School",
    "Horse Trailer Dealer",
    "Horse Trainer",
    "Horseback Riding Service",
    "Horticulture Company",
    "Hospice",
    "Hospital",
    "Hospital Equipment and Supplies Store",
    "Hostel",
    "Hot Dog Restaurant",
    "Hot Spring",
    "Hot Tub Repair Service",
    "Hot Tub Store",
    "Hot Water System Supplier",
    "Hotel",
    "Hotel Management Company",
    "Hotel Supply Store",
    "House Cleaning Service",
    "House Sitter",
    "Houseboat Rental Service",
    "Housing Authority",
    "Housing Cooperative",
    "Human Resource Consulting Firm",
    "Human Rights Organization",
    "Hungarian Restaurant",
    "Hunting and Fishing Store",
    "Hunting Club",
    "Hunting Preserve",
    "Hydraulic Equipment Supplier",
    "Hydraulic Repair Service",
    "Hydraulic Tools Supplier",
    "Hydroponics Equipment Supplier",
    "Hypnotherapy Service",
    "Hyundai Dealer",
    "Ice Cream Equipment Supplier",
    "Ice Cream Shop",
    "Ice Skating Club",
    "Ice Skating Instructor",
    "Ice Skating Rink",
    "Icelandic Restaurant",
    "Ignition Interlock Device Supplier",
    "IKO Roofing Contractor",
    "Imaging Center",
    "Immigration Attorney",
    "Immigration Detention Center",
    "Importer",
    "Inbound Tour Agency",
    "Incense Supplier",
    "Indian Grocery Store",
    "Indian Restaurant",
    "Indoor Cycling Instructor",
    "Indoor Golf Course",
    "Indoor Playground",
    "Indoor Ski Resort",
    "Industrial Chemicals Supplier",
    "Industrial Design Company",
    "Industrial Door Supplier",
    "Industrial Engineer",
    "Industrial Equipment Supplier",
    "Industrial Gas Supplier",
    "Industrial Heating Equipment Supplier",
    "Industrial Hygiene Service",
    "Industrial Land Development Company",
    "Industrial Vacuum Equipment Supplier",
    "Infectious Disease Physician",
    "Infertility Clinic",
    "Information Bureau",
    "Information Retrieval Service",
    "Information Technology Company",
    "Inhalation Therapy Practitioner",
    "Injection Molding Service",
    "Inn",
    "Insect Control Service",
    "Insecticides Wholesaler",
    "Installation Service",
    "Instant Printing Service",
    "Instructional Materials Store",
    "Instrumentation Engineer",
    "Insulation Contractor",
    "Insulation Materials Supplier",
    "Insurance Agency",
    "Insurance Broker",
    "Insurance School",
    "Integrated Circuit Designer",
    "Intellectual Property Attorney",
    "Intellectual Property Registry",
    "Interior Designer",
    "Interior Door Supplier",
    "Interior Plant Service",
    "International Airport",
    "International Trade Consultant",
    "Internet Cafe",
    "Internet Marketing Service",
    "Internet Service Provider",
    "Interpretation Service",
    "Investment Bank",
    "Investment Company",
    "Investment Service",
    "Irish Goods Store",
    "Irish Pub",
    "Iron Works",
    "Irrigation Equipment Supplier",
    "Italian Grocery Store",
    "Italian Restaurant",
    "IT Consultant",
    "IT Security Service",
    "Janitorial Equipment Supplier",
    "Janitorial Service",
    "Japanese Grocery Store",
    "Japanese Restaurant",
    "Jazz Club",
    "Jehovah's Witness Church",
    "Jeweler",
    "Jewelry Appraiser",
    "Jewelry Buyer",
    "Jewelry Designer",
    "Jewelry Engraver",
    "Jewelry Equipment Supplier",
    "Jewelry Repair Service",
    "Jewelry Store",
    "Jewish Cemetery",
    "Jewish Synagogue",
    "Juice Shop",
    "Jujitsu School",
    "Junkyard",
    "Karaoke Bar",
    "Karaoke Equipment Supplier",
    "Karate School",
    "Kennel",
    "Kerosene Supplier",
    "Key Duplication Service",
    "Keychain Supplier",
    "Kickboxing School",
    "Kidney Dialysis Center",
    "Kitchen Remodeler",
    "Kitchen Supply Store",
    "Kite Shop",
    "Knitting Store",
    "Korean Grocery Store",
    "Korean Restaurant",
    "Kosher Grocery Store",
    "Kosher Restaurant",
    "Labeling Equipment Supplier",
    "Laboratory Equipment Supplier",
    "Laboratory Testing Service",
    "Labrador Retriever Breeder",
    "Lake",
    "Land Planning Services",
    "Land Surveyor",
    "Landscape Architect",
    "Landscape Designer",
    "Landscape Lighting Designer",
    "Language School",
    "Laser Cutting Service",
    "Laser Equipment Supplier",
    "Laser Hair Removal Service",
    "Laser Tag Center",
    "Latin American Grocery Store",
    "Latin American Restaurant",
    "Laundry Service",
    "Law Firm",
    "Lawn Care Service",
    "Lawn Equipment Rental Service",
    "Lawn Irrigation Equipment Supplier",
    "Lawn Sprinkler System Contractor",
    "Lead Generation Service",
    "Leather Goods Store",
    "Lebanese Grocery Store",
    "Lebanese Restaurant",
    "Legal Services",
    "Leisure Centre",
    "Library",
    "License Bureau",
    "License Plate Frames Supplier",
    "Licensing Agency",
    "Life Coach",
    "Life Insurance Agency",
    "Lighting Consultant",
    "Lighting Contractor",
    "Lighting Manufacturer",
    "Lighting Store",
    "Lighting Wholesaler",
    "Limousine Service",
    "Linen Rental Service",
    "Linens Supplier",
    "Lingerie Store",
    "Livestock Auction House",
    "Livestock Breeder",
    "Livestock Dealer",
    "Livestock Farm",
    "Livestock Feeder Supplier",
    "Livestock Producer",
    "Livestock Transport Service",
    "Loan Agency",
    "Loan Broker",
    "Loan Modification Service",
    "Lock Repair Service",
    "Locksmith",
    "Loft Conversion Specialist",
    "Logistics Service",
    "Machine Repair Service",
    "Machine Shop",
    "Machine Tool Manufacturer",
    "Machinery Parts Manufacturer",
    "Magician",
    "Maid Service",
    "Mailbox Rental Service",
    "Mailing Machine Supplier",
    "Make-Up Artist",
    "Malaysian Grocery Store",
    "Malaysian Restaurant",
    "Management Consultant",
    "Management School",
    "Mandap Supplier",
    "Manufacturer",
    "Marble Contractor",
    "Marble Supplier",
    "Marine Supply Store",
    "Market Researcher",
    "Marketing Agency",
    "Marketing Consultant",
    "Marketing School",
    "Marriage Counselor",
    "Martial Arts School",
    "Masonry Contractor",
    "Massage School",
    "Massage Spa",
    "Massage Supply Store",
    "Maternity Store",
    "Mattress Cleaning Service",
    "Mattress Store",
    "Meadery",
    "Meal Delivery Service",
    "Meal Takeaway",
    "Meat Processor",
    "Meat Wholesaler",
    "Media and Communication Consultant",
    "Mediation Service",
    "Medical Billing Service",
    "Medical Clinic",
    "Medical Equipment Manufacturer",
    "Medical Equipment Repair Service",
    "Medical Equipment Supplier",
    "Medical Group",
    "Medical Laboratory",
    "Medical School",
    "Medical Spa",
    "Medical Supply Store",
    "Medical Transcription Service",
    "Meditation Center",
    "Mediterranean Grocery Store",
    "Mediterranean Restaurant",
    "Men's Clothing Store",
    "Men's Hair Salon",
    "Men's Health Clinic",
    "Men's Store",
    "Mental Health Clinic",
    "Mental Health Service",
    "Metal Detecting Equipment Supplier",
    "Metal Fabricator",
    "Metal Finishing Service",
    "Metal Heat Treating Service",
    "Metal Polishing Service",
    "Metal Supplier",
    "Mexican Grocery Store",
    "Mexican Restaurant",
    "Middle Eastern Grocery Store",
    "Middle Eastern Restaurant",
    "Midwife",
    "Military Base",
    "Military School",
    "Milk Delivery Service",
    "Millwork Shop",
    "Miniature Golf Course",
    "Mining Company",
    "Mirror Shop",
    "Miscellaneous Store",
    "Mobile Billboard Advertising Service",
    "Mobile Crane Service",
    "Mobile Home Dealer",
    "Mobile Home Park",
    "Mobile Home Rental Agency",
    "Mobile Home Supply Store",
    "Mobile Notary",
    "Mobile Phone Repair Service",
    "Mobile Phone Shop",
    "Mobile Veterinarian",
    "Model Design Company",
    "Modeling Agency",
    "Modern Art Museum",
    "Mold Inspection Service",
    "Mold Remediation Service",
    "Mold Supplier",
    "Monastery",
    "Money Order Service",
    "Money Transfer Service",
    "Mongolian Restaurant",
    "Monument Maker",
    "Mortgage Broker",
    "Mortgage Lender",
    "Motel",
    "Motorcycle Dealer",
    "Motorcycle Driving School",
    "Motorcycle Insurance Agency",
    "Motorcycle Rental Agency",
    "Motorcycle Repair Shop",
    "Motorcycle Shop",
    "Motorcycle Training Center",
    "Motorcycle Wholesaler",
    "Motivational Speaker",
    "Motor Scooter Dealer",
    "Motor Vehicle Dealer",
    "Motor Vehicle Registration Office",
    "Motor Vehicle Rental Agency",
    "Motor Vehicle Valuation Service",
    "Motorbike Shop",
    "Motorhome Dealer",
    "Motorhome Rental Agency",
    "Motorhome Service",
    "Motorcycle and Scooter Parking Area",
    "Moulding Supplier",
    "Muffler Repair Shop",
    "Mulch Supplier",
    "Multimedia and Electronic Book Publisher",
    "Multimedia and Electronic Book Store",
    "Multimedia and Electronic Book Subscription Service",
    "Municipal Engineer",
    "Municipal Government Office",
    "Municipal Park",
    "Municipal Recycling Center",
    "Municipal Sports Center",
    "Municipal Sports Stadium",
    "Murals Artist",
    "Museum",
    "Museum of Archaeology",
    "Museum of Art",
    "Museum of Natural History",
    "Music Box Store",
    "Music Instructor",
    "Music Management and Promotion",
    "Music Producer",
    "Music Production Studio",
    "Music School",
    "Music Store",
    "Music Venue",
    "Musical Instrument Manufacturer",
    "Musical Instrument Rental Service",
    "Musical Instrument Repair Shop",
    "Musical Instrument Store",
    "Musical Theater",
    "Nanny Service",
    "Natural Foods Store",
    "Natural Gas Supplier",
    "Natural Health Products Store",
    "Natural History Museum",
    "Naturopathic Medicine Practitioner",
    "Navy",
    "Necktie Store",
    "Needlework Shop",
    "Neon Sign Shop",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "New Age Church",
    "New Car Dealer",
    "News Service",
    "Newsstand",
    "Newspaper Advertising Department",
    "Newspaper Publisher",
    "Night Club",
    "Night Market",
    "Night Safari",
    "Noodle Shop",
    "Notary Public",
    "Nurseries and Greenhouses",
    "Nursery School",
    "Nursing Agency",
    "Nursing Home",
    "Nutritionist",
    "Obstetrician-Gynecologist",
    "Occupational Health Service",
    "Occupational Therapist",
    "Office Equipment Rental Service",
    "Office Furniture Store",
    "Office Space Rental Agency",
    "Office Supply Store",
    "Ophthalmologist",
    "Optical Goods Store",
    "Optician",
    "Optometrist",
    "Orchid Farm",
    "Organic Drug Store",
    "Organic Food Store",
    "Organic Restaurant",
    "Organizational Psychologist",
    "Oriental Medicine Clinic",
    "Orphanage",
    "Orthodontist",
    "Orthopedic Shoe Store",
    "Orthopedic Surgeon",
    "Orthotics & Prosthetics Service",
    "Osteopath",
    "Outdoor Clothing Store",
    "Outdoor Furniture Store",
    "Outdoor Sports Store",
    "Outlet Mall",
    "Outlet Store",
    "Oven Repair Service",
    "Packaging Supply Store",
    "Paddleboarding Center",
    "Paint Manufacturer",
    "Paint Store",
    "Painter",
    "Palaeontologist",
    "Paper Distributor",
    "Paper Mill",
    "Paragliding Club",
    "Paramedic",
    "Parasailing Ride Service",
    "Parenting Counselor",
    "Park",
    "Parking Garage",
    "Parking Lot",
    "Passport Office",
    "Patio Enclosure Supplier",
    "Patio Furniture Store",
    "Pawn Shop",
    "Payphone",
    "Pediatric Dentist",
    "Pediatrician",
    "Peking Duck Restaurant",
    "Pen Store",
    "Pension Consultant",
    "Pentecostal Church",
    "Percussion Instrument Store",
    "Periodontist",
    "Permanent Makeup Clinic",
    "Persian Carpet Store",
    "Personal Chef",
    "Personal Injury Attorney",
    "Personal Trainer",
    "Pest Control Service",
    "Pet Adoption Service",
    "Pet Cemetery",
    "Pet Groomer",
    "Pet Sitter",
    "Pet Supply Store",
    "Pet Training Service",
    "Petting Zoo",
    "Pharmaceutical Company",
    "Pharmacist",
    "Pharmacy",
    "Phone Repair Service",
    "Photo Lab",
    "Photocopier Supplier",
    "Photographer",
    "Photography School",
    "Physical Fitness Program",
    "Physical Therapist",
    "Physician",
    "Piano Bar",
    "Piano Instructor",
    "Piano Moving Service",
    "Picture Frame Shop",
    "Piercing Shop",
    "Pilates Studio",
    "Pipe Supplier",
    "Pizza Delivery",
    "Pizza Restaurant",
    "Plant Nursery",
    "Plasterer",
    "Plastic Bag Supplier",
    "Plastic Fabrication Company",
    "Plastic Injection Molding Service",
    "Plastic Surgeon",
    "Playground",
    "Plumber",
    "Plumbing Supply Store",
    "Podiatrist",
    "Police Department",
    "Polish Restaurant",
    "Political Organization",
    "Pond Contractor",
    "Pool Cleaning Service",
    "Pool Hall",
    "Pool Supply Store",
    "Popcorn Store",
    "Portuguese Restaurant",
    "Post Office",
    "Poultry Farm",
    "Powder Coating Service",
    "Power Plant",
    "Preschool",
    "Pressure Washing Service",
    "Pretzel Store",
    "Printer Repair Service",
    "Printing Service",
    "Private Investigator",
    "Private School",
    "Probate Attorney",
    "Process Server",
    "Produce Market",
    "Product Design Consultant",
    "Professional Organizer",
    "Project Management Consultant",
    "Promotional Products Supplier",
    "Property Management Company",
    "Psychiatric Hospital",
    "Psychiatrist",
    "Psychic",
    "Psychoanalyst",
    "Psychotherapist",
    "Public Relations Firm",
    "Public Swimming Pool",
    "Public Notary",
    "Public Relations Consultant",
    "Public Transit Line",
    "Publisher",
    "Publishing Company",
    "Pulmonologist",
    "Pump Supplier",
    "Quilt Shop",
    "RV Dealer",
    "RV Park",
    "RV Rental Agency",
    "Racecourse",
    "Racing Car Parts Store",
    "Radiator Repair Service",
    "Radiologist",
    "Raft Trip Outfitter",
    "Railroad Company",
    "Railway Station",
    "Ranch",
    "Real Estate Agency",
    "Real Estate Agents",
    "Real Estate Appraiser",
    "Real Estate Attorney",
    "Real Estate Rental Agency",
    "Recording Studio",
    "Recreational Vehicle Rental Agency",
    "Recycling Center",
    "Reflexologist",
    "Refrigerator Repair Service",
    "Rehabilitation Center",
    "Religious Goods Store",
    "Religious Institution",
    "Religious Organization",
    "Rental Service",
    "Repair Service",
    "Research Foundation",
    "Residential Construction Company",
    "Residential Designer",
    "Resort",
    "Restaurant",
    "Restaurant Supply Store",
    "Retirement Community",
    "Retirement Home",
    "Rheumatologist",
    "Roadside Assistance Service",
    "Rock Climbing Gym",
    "Roofing Contractor",
    "Roofing Supply Store",
    "Roommate Referral Service",
    "Rubbish Removal Service",
    "RV Park",
    "RV Storage Facility",
    "Race Car Dealer",
    "Race Track",
    "Racing Car Parts Store",
    "Racing Car Dealer",
    "Racquetball Club",
    "Radiator Repair Service",
    "Radiologist",
    "Raft Trip Outfitter",
    "Railroad Company",
    "Railway Equipment Supplier",
    "Railway Station",
    "Ranch",
    "Ranch Supply Store",
    "Real Estate Agency",
    "Real Estate Agents",
    "Real Estate Appraiser",
    "Real Estate Attorney",
    "Real Estate Consultant",
    "Real Estate Developer",
    "Real Estate Rental Agency",
    "Recording Studio",
    "Record Label",
    "Recreational Vehicle Rental Agency",
    "Recreational Vehicle Repair Service",
    "Recycling Center",
    "Reflexologist",
    "Refrigerator Repair Service",
    "Rehabilitation Center",
    "Religious Bookstore",
    "Religious Goods Store",
    "Religious Institution",
    "Religious Organization",
    "Religious School",
    "Remodeler",
    "Rendering Service",
    "Renovation Contractor",
    "Rental Service",
    "Repo Auction",
    "Research Foundation",
    "Research Institute",
    "Research Laboratory",
    "Residential Building",
    "Residential Cleaning Service",
    "Residential Construction Company",
    "Residential Designer",
    "Residential Estate",
    "Residential Homebuilder",
    "Residential Treatment Center",
    "Resort",
    "Respiratory Therapist",
    "Restaurant",
    "Retirement Community",
    "Retirement Home",
    "Rheumatologist",
    "Rib Restaurant",
    "Rice Restaurant",
    "Riding School",
    "Road Construction Company",
    "Roadside Assistance Service",
    "Rock Climbing Gym",
    "Rock Climbing Instructor",
    "Rock Shop",
    "Roller Skating Rink",
    "Roofing Contractor",
    "Roofing Supply Store",
    "Roommate Referral Service",
    "Ropes Course",
    "Rotisserie Chicken Restaurant",
    "Rowing Club",
    "Rubbish Dump",
    "Rubbish Removal Service",
    "Rugby Club",
    "Running Store",
    "Russian Orthodox Church",
    "RV Dealer",
    "RV Park",
    "RV Rental Agency",
    "RV Repair Shop",
    "Safety Equipment Supplier",
    "Saigon Restaurant",
    "Salad Shop",
    "Salsa Club",
    "Salvage Yard",
    "Sandblasting Service",
    "Sandwich Shop",
    "Sanitation Service",
    "Santoku Restaurant",
    "Sausage Shop",
    "Sauna",
    "Scaffolding Rental Service",
    "Scale Supplier",
    "Scandinavian Restaurant",
    "Scenic Spot",
    "School Bus Service",
    "School District Office",
    "School Supply Store",
    "Science Museum",
    "Scuba Instructor",
    "Seafood Market",
    "Seafood Restaurant",
    "Seafood Wholesale",
    "Self Defense School",
    "Self-Service Car Wash",
    "Self-Storage Facility",
    "Senior Citizen Center",
    "Serbian Orthodox Church",
    "Serviced Apartment Building",
    "Sewing Company",
    "Sewing Machine Repair Service",
    "Sewing Supply Store",
    "Sex Therapist",
    "Share House",
    "Sheet Metal Contractor",
    "Shipping and Mailing Service",
    "Shipyard",
    "Shoe Repair Shop",
    "Shoe Store",
    "Shooting Range",
    "Shopping Mall",
    "Shredding Service",
    "Shrimp Wholesaler",
    "Shrub Nursery",
    "Shutter Store",
    "Siberian Restaurant",
    "Sign Shop",
    "Sikh Temple",
    "Silk Plant Shop",
    "Silverware Store",
    "Skate Sharpening Service",
    "Skate Shop",
    "Skating Rink",
    "Ski Lodge",
    "Ski Rental Service",
    "Ski Resort",
    "Ski School",
    "Skin Care Clinic",
    "Skydiving Center",
    "Sledding Hill",
    "Sleep Clinic",
    "Sleepwear Store",
    "Slushie Machine Supplier",
    "Small Appliance Repair Service",
    "Small Claims Assistance Service",
    "Small Plates Restaurant",
    "Smart Home Automation Company",
    "Smog Inspection Station",
    "Smoke Shop",
    "Smokehouse",
    "Smoothie Shop",
    "Snack Bar",
    "Snorkeling Tour Agency",
    "Snow Removal Service",
    "Snowboard Rental Service",
    "Snowmobile Rental Service",
    "Social Security Attorney",
    "Social Security Office",
    "Social Services Organization",
    "Sock Store",
    "Software Company",
    "Solar Energy Company",
    "Solar Energy Equipment Supplier",
    "Solar Hot Water System Supplier",
    "Solar Installation Company",
    "Solar Photovoltaic System Supplier",
    "Solar Power Company",
    "Solar Power Plant",
    "Solar System Designer",
    "Souvenir Store",
    "Spa",
    "Spanish Language School",
    "Spanish Restaurant",
    "Spay and Neuter Clinic",
    "Special Education School",
    "Specialty Food Store",
    "Specialty School",
    "Speech Pathologist",
    "Speed Dating Service",
    "Spice Store",
    "Sporting Goods Store",
    "Sports Bar",
    "Sports Card Store",
    "Sports Center",
    "Sports Club",
    "Sports Complex",
    "Sports Medicine Clinic",
    "Sports Memorabilia Store",
    "Sports Nutrition Store",
    "Sports School",
    "Sports Store",
    "Sports Training Facility",
    "Spray Foam Insulation Contractor",
    "Spring Supplier",
    "Sprinkler Contractor",
    "Sprinkler System Contractor",
    "Sprinkler System Supplier",
    "Squash Club",
    "Stables",
    "Stadium",
    "Stained Glass Studio",
    "Stair Contractor",
    "Stair Lift Supplier",
    "Stamp Shop",
    "Stationery Store",
    "Steak House",
    "Steam Room Supplier",
    "Steel Distributor",
    "Steel Drum Supplier",
    "Steel Fabricator",
    "Steel Frame Supplier",
    "Steel Supplier",
    "Stenographer",
    "Step Stool Supplier",
    "Stockbroker",
    "Stone Supplier",
    "Stonemason",
    "Storage Facility",
    "Storm Shutter Contractor",
    "Storm Water Drainage Contractor",
    "Stormwater Management Service",
    "Street Sweeper Supplier",
    "Structural Engineer",
    "Structural Steel Contractor",
    "Stucco Contractor",
    "Student Accommodation Center",
    "Student Housing Center",
    "Subaru Dealer",
    "Suede Store",
    "Sugar Mill",
    "Sugaring Hair Removal Service",
    "Sunroom Contractor",
    "Supermarket",
    "Supplement Shop",
    "Surgeon",
    "Surgical Center",
    "Surgical Supply Store",
    "Surveyor",
    "Sushi Restaurant",
    "Suzuki Dealer",
    "Swim Club",
    "Swim School",
    "Swim Spa Supplier",
    "Swimming Pool Contractor",
    "Swimming Pool Repair Service",
    "Swimming Pool Supply Store",
    "Swimwear Store",
    "Synagogue",
    "T-Shirt Company",
    "Table and Chair Rental Service",
    "Table Tennis Club",
    "Taco Restaurant",
    "Tailor",
    "Taiwanese Restaurant",
    "Takeout Restaurant",
    "Talent Agency",
    "Tanning Salon",
    "Tapas Bar",
    "Tattoo Removal Service",
    "Tattoo Shop",
    "Tax Consultant",
    "Taxi Service",
    "Tea House",
    "Tea Store",
    "Tearoom",
    "Technical School",
    "Telecommunications Contractor",
    "Telecommunications Equipment Supplier",
    "Telecommunications Service Provider",
    "Telecommunications Tower",
    "Telemarketing Service",
    "Telephone Answering Service",
    "Television Repair Service",
    "Television Station",
    "Temp Agency",
    "Tempura Restaurant",
    "Tennis Club",
    "Tennis Court",
    "Tennis Instructor",
    "Tennis Store",
    "Tent Rental Service",
    "Thai Massage Therapist",
    "Thai Restaurant",
    "Thatched Cottage",
    "Theatrical Company",
    "Theme Park",
    "Therapeutic Massage",
    "Thrift Store",
    "Tibetan Restaurant",
    "Tile Contractor",
    "Tile Store",
    "Timber Merchants",
    "Time and Attendance Software Company",
    "Tire Shop",
    "Title Company",
    "Tobacco Shop",
    "Tofu Shop",
    "Tomato Supplier",
    "Tour Agency",
    "Tour Operator",
    "Tourist Attraction",
    "Tourist Information Center",
    "Tower Crane Supplier",
    "Townhouse Complex",
    "Toy Store",
    "Toyota Dealer",
    "Toyota Repair Shop",
    "Track Field Stadium",
    "Tractor Dealer",
    "Tractor Equipment Supplier",
    "Tractor Repair Shop",
    "Trade School",
    "Trading Card Store",
    "Traditional Chinese Medicine Clinic",
    "Traffic Attorney",
    "Traffic School",
    "Trailer Dealer",
    "Trailer Hitch Supplier",
    "Trailer Manufacturer",
    "Trailer Rental Service",
    "Trailer Repair Shop",
    "Train Ticket Agency",
    "Train Station",
    "Trainee Recruitment Consultant",
    "Transcription Service Provider",
    "Transmission Shop",
    "Transport Company",
    "Transportation Escort Service",
    "Transportation Service",
    "Travel Agency",
    "Travel Medicine Clinic",
    "Tree Farm",
    "Tree Service",
    "Tree Stump Removal Service",
    "Trenching Contractor",
    "Trichologist",
    "Truck Accessories Store",
    "Truck Dealer",
    "Truck Rental Agency",
    "Truck Repair Shop",
    "Truck Stop",
    "Trucking Company",
    "Trucking School",
    "Trucking Transportation Broker",
    "Trucking Warehouse",
    "Truffle Shop",
    "Trust and Estate Attorney",
    "Tube Well Drilling Service",
    "Tugboat Service",
    "Tuning Automobile",
    "Tunnel Construction Company",
    "Turbocharger Repair Service",
    "Turkish Restaurant",
    "Turntable Manufacturer",
    "Tutoring Service",
    "TV Repair Service",
    "TV Station",
    "TV Station Equipment Supplier",
    "Tuxedo Shop",
    "Typewriter Repair Service",
    "Typing Service",
    "Typographic Design Agency",
    "Tyre Retreading Shop",
    "Tyre Shop",
    "Tyre Wholesaler",
    "Ultrasound Imaging Center",
    "Unemployment Insurance Consultant",
    "Uniform Store",
    "Unitarian Universalist Church",
    "University",
    "Upholstery Cleaning Service",
    "Upholstery Shop",
    "Urban Planning Department",
    "Urgent Care Center",
    "Used Appliance Store",
    "Used Bicycle Shop",
    "Used Bookstore",
    "Used Car Dealer",
    "Used CD Store",
    "Used Clothing Store",
    "Used Computer Store",
    "Used Furniture Store",
    "Used Musical Instrument Store",
    "Used Office Furniture Store",
    "Used Sporting Goods Store",
    "Used Tire Shop",
    "Used Truck Dealer",
    "Used Video Game Store",
    "Utility Contractor",
    "Vacuum Cleaner Repair Service",
    "Vacuum Cleaner Store",
    "Valet Parking Service",
    "Van Rental Agency",
    "Vape Shop",
    "Variety Store",
    "Vascular Surgeon",
    "Vehicle Inspection Station",
    "Vehicle Shipping Agent",
    "Vehicle Signage Shop",
    "Vehicle Testing Center",
    "Vending Machine Supplier",
    "Venetian Blind Supplier",
    "Venetian Restaurant",
    "Veterinarian",
    "Veterinary Pharmacy",
    "Veterinary Pharmacy",
    "Veterinary Radiologist",
    "Veterinary Referral Hospital",
    "Veterinary Surgeon",
    "Vietnamese Restaurant",
    "Villa Rental Agency",
    "Vinyl Fence Contractor",
    "Vinyl Records Store",
    "Vinyl Siding Contractor",
    "Violin Shop",
    "Virtual Reality Arcade",
    "Vitamins & Supplements Store",
    "Vocational School",
    "Voice Over Artist",
    "Volleyball Club",
    "Volvo Dealer",
    "Wallpaper Store",
    "Warehouse Club",
    "Warehouse Store",
    "Watch Repair Service",
    "Watch Store",
    "Water Damage Restoration Service",
    "Water Heater Installation & Repair Service",
    "Water Purification Company",
    "Water Ski Shop",
    "Water Skiing Instructor",
    "Water Softening Equipment Supplier",
    "Water Testing Service",
    "Water Treatment Supplier",
    "Water Utility Company",
    "Waterproofing Company",
    "Waxing Hair Removal Service",
    "Web Hosting Company",
    "Web Traffic School",
    "Website Designer",
    "Wedding Bakery",
    "Wedding Boutique",
    "Wedding Chapel",
    "Wedding Photographer",
    "Wedding Planner",
    "Wedding Videographer",
    "Weight Loss Center",
    "Welding Gas Supplier",
    "Welding Supply Store",
    "Well Drilling Contractor",
    "Wellness Center",
    "Wheelchair Rental Service",
    "Wheelchair Repair Service",
    "Wheelchair Store",
    "Wholesaler",
    "Wholesale Bakery",
    "Wholesale Florist",
    "Wholesale Grocer",
    "Wholesale Plant Nursery",
    "Wholesale Seafood Supplier",
    "Wigs and Hairpieces Store",
    "Wildlife Refuge",
    "Window Cleaning Service",
    "Window Installation Service",
    "Window Supplier",
    "Window Tinting Service",
    "Window Treatment Store",
    "Windshield Repair Service",
    "Wine Bar",
    "Wine Store",
    "Winery",
    "Women's Clothing Store",
    "Women's Health Clinic",
    "Women's Shelter",
    "Work Clothes Store",
    "Workplace Safety Equipment Supplier",
    "Wrestling School",
    "Writing Service",
    "X-ray Imaging Service",
    "Yacht Broker",
    "Yarn Store",
    "Yoga Studio",
    "Youth Center",
    "Youth Organization",
    "Zipline",
    "Zoo",
    "Zoological Garden",
]
