---
- name: Check if kubectl is already installed
  command: kubectl version --client --output=yaml
  register: kubectl_check
  failed_when: false
  changed_when: false

- name: Download kubectl binary if not installed or wrong version
  get_url:
    url: https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: yes
  when: "'gitVersion: v1.30.1' not in kubectl_check.stdout"

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- name: Show kubectl version
  debug:
    var: kubectl_version.stdout