---
- name: Download kubectl binary
  get_url:
    url: https://dl.k8s.io/release/v1.30.1/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    force: yes

- name: Verify kubectl installation
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- name: Show kubectl version
  debug:
    var: kubectl_version.stdout 