// Import BusinessSchema from the original file
import fs from 'fs';

import convertSchemaToInterface from './convertSchemaToInterface';
import { BusinessSchema } from '../validators/Business';
import { BusinessCategorySchema } from '../validators/BusinessCategory';
import { BusinessClosingHourSchema } from '../validators/BusinessClosingHour';
import { BusinessOpeningHourSchema } from '../validators/BusinessOpeningHour';
import { BusinessPhoneSchema } from '../validators/BusinessPhone';
import { BusinessPhotoSchema } from '../validators/BusinessPhoto';
import { BusinessRatingSchema } from '../validators/BusinessRating';
import { BusinessSocialMediaSchema } from '../validators/BusinessSocialMedia';
import { BusinessSourceSchema } from '../validators/BusinessSource';
import { CitySchema } from '../validators/City';
import { CountrySchema } from '../validators/Country';
import { GeoPointSchema } from '../validators/GeoPoint';
import { LeadSchema } from '../validators/Lead';
import { LeadBusinessSchema } from '../validators/LeadBusiness';
import { PaginationSchema } from '../validators/Pagination';
import { PostalCodeSchema } from '../validators/PostalCode';
import { QueueSchema } from '../validators/Queue';
import { RequestSchema } from '../validators/Request';
import { StateSchema } from '../validators/State';
import { TimezoneSchema } from '../validators/Timezone';
import { UserSchema, LoginSchema } from '../validators/User';

const ILoginRequestInterface = convertSchemaToInterface(LoginSchema, 'ILoginRequestAttributes');
const IBusinessInterface = convertSchemaToInterface(BusinessSchema, 'IBusinessAttributes');
const IBusinessCategoryInterface = convertSchemaToInterface(BusinessCategorySchema, 'IBusinessCategoryAttributes');
const IBusinessClosingHourInterface = convertSchemaToInterface(BusinessClosingHourSchema, 'IBusinessClosingHourAttributes');
const IBusinessOpeningHourInterface = convertSchemaToInterface(BusinessOpeningHourSchema, 'IBusinessOpeningHourAttributes');
const IBusinessPhoneInterface = convertSchemaToInterface(BusinessPhoneSchema, 'IBusinessPhoneAttributes');
const IBusinessPhotoInterface = convertSchemaToInterface(BusinessPhotoSchema, 'IBusinessPhotoAttributes');
const IBusinessRatingInterface = convertSchemaToInterface(BusinessRatingSchema, 'IBusinessRatingAttributes');
const IBusinessSocialMediaInterface = convertSchemaToInterface(BusinessSocialMediaSchema, 'IBusinessSocialMediaAttributes');
const IBusinessSourceInterface = convertSchemaToInterface(BusinessSourceSchema, 'IBusinessSourceAttributes');
const ICityInterface = convertSchemaToInterface(CitySchema, 'ICityAttributes');
const ICountryInterface = convertSchemaToInterface(CountrySchema, 'ICountryAttributes');
const IGeoPointInterface = convertSchemaToInterface(GeoPointSchema, 'IGeoPointAttributes');
const ILeadInterface = convertSchemaToInterface(LeadSchema, 'ILeadAttributes');
const ILeadBusinessInterface = convertSchemaToInterface(LeadBusinessSchema, 'ILeadBusinessAttributes');
const IPaginationInterface = convertSchemaToInterface(PaginationSchema, 'IPaginationAttributes');
const IPostalCodeInterface = convertSchemaToInterface(PostalCodeSchema, 'IPostalCodeAttributes');
const IQueueInterface = convertSchemaToInterface(QueueSchema, 'IQueueAttributes');
const IRequestInterface = convertSchemaToInterface(RequestSchema, 'IRequestAttributes');
const IStateInterface = convertSchemaToInterface(StateSchema, 'IStateAttributes');
const IUserInterface = convertSchemaToInterface(UserSchema, 'IUserAttributes');
const ITimezoneInterface = convertSchemaToInterface(TimezoneSchema, 'ITimezoneAttributes');

// Write the generated interface to the file
fs.writeFileSync('interface/IBusinessInterface.ts', IBusinessInterface);
fs.writeFileSync('interface/IBusinessCategoryInterface.ts', IBusinessCategoryInterface);
fs.writeFileSync('interface/IBusinessClosingHourInterface.ts', IBusinessClosingHourInterface);
fs.writeFileSync('interface/IBusinessOpeningHourInterface.ts', IBusinessOpeningHourInterface);
fs.writeFileSync('interface/IBusinessPhoneInterface.ts', IBusinessPhoneInterface);
fs.writeFileSync('interface/IBusinessPhotoInterface.ts', IBusinessPhotoInterface);
fs.writeFileSync('interface/IBusinessRatingInterface.ts', IBusinessRatingInterface);
fs.writeFileSync('interface/IBusinessSocialMediaInterface.ts', IBusinessSocialMediaInterface);
fs.writeFileSync('interface/IBusinessSourceInterface.ts', IBusinessSourceInterface);
fs.writeFileSync('interface/ICityInterface.ts', ICityInterface);
fs.writeFileSync('interface/ICountryInterface.ts', ICountryInterface);
fs.writeFileSync('interface/IGeoPointInterface.ts', IGeoPointInterface);
fs.writeFileSync('interface/ILeadInterface.ts', ILeadInterface);
fs.writeFileSync('interface/ILeadBusinessInterface.ts', ILeadBusinessInterface);
fs.writeFileSync('interface/IPaginationInterface.ts', IPaginationInterface);
fs.writeFileSync('interface/IPostalCodeInterface.ts', IPostalCodeInterface);
fs.writeFileSync('interface/IQueueInterface.ts', IQueueInterface);
fs.writeFileSync('interface/IRequestInterface.ts', IRequestInterface);
fs.writeFileSync('interface/IStateInterface.ts', IStateInterface);
fs.writeFileSync('interface/IUserInterface.ts', IUserInterface);
fs.writeFileSync('interface/ILoginRequestAttributes.ts', ILoginRequestInterface);
fs.writeFileSync('interface/ITimezoneInterface.ts', ITimezoneInterface);
