apiVersion: apps/v1
kind: Deployment
metadata:
  name: troophunter-landing-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: troophunter-landing-prod
  template:
    metadata:
      labels:
        app: troophunter-landing-prod
    spec:
      containers:
        - name: troophunter-landing-prod
          image: troophunter-landing-prod:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/start.sh"]
          ports:
            - containerPort: 3000
            - containerPort: 5173
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: logs
              mountPath: /microfrontend/troophunter-landing/logs
      volumes:
        - name: logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: troophunter-landing-prod
spec:
  selector:
    app: troophunter-landing-prod
  ports:
    - name: landing-http
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: troophunter-http
      protocol: TCP
      port: 5173
      targetPort: 5173