---
- hosts: ubuntu
  # user: ubuntu-server
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - /ansible/secrets/github_token
  vars:
    USER: ubuntu-server
    NODE_VERSION: 20.12.2
    GIT_REPO: "https://{{ github_token }}@github.com/helloabdul/TroopHunterNew.git"
    GIT_BRANCH: staging
    PROJECT_NAME: TroopHunter
    ENVIRONMENT: stag
    ENV_PATH: "/ansible/secrets"
    # PROTONVPN_USERNAME: alrazzaq1971@gmail.com
    # PROTONVPN_PASSWORD: 7!>G^dmkmwwWbc50
    # PROTONVPN_SERVER: US-NY#627
  gather_facts: true
  roles:
    # - proton
    # - common
    # - nvm
    # - node
    # - docker
    - github
    - project