DELETE FROM "BusinessPhotos";
DELETE FROM "Businesses";
DELETE FROM "BusinessCategories";
DELETE FROM "Days";
DELETE FROM "OpeningHours";
DELETE FROM "ClosingHours";
DELETE FROM "BusinessDays";
DELETE FROM "BusinessOpeningHours";
DELETE FROM "BusinessClosingHours";
DELETE FROM "BusinessPhones";
DELETE FROM "BusinessRatings";
DELETE FROM "BusinessSocialMedia";
DELETE FROM "BusinessSources";
DELETE FROM "Leads";
-- DELETE FROM "Lists";
DELETE FROM "PostalCodes";
-- DELETE FROM "SequelizeMeta";
DELETE FROM "Timezones";
-- DELETE FROM "Queues";
-- DELETE FROM "CityQueues";
