-- Drop BusinessPhoto table
DROP TABLE IF EXISTS "LeadBusinesses";
DROP TABLE IF EXISTS "BusinessPhotos";
DROP TABLE IF EXISTS "Leads";
DROP TABLE IF EXISTS "Businesses";
DROP TABLE IF EXISTS "BusinessCategories";
DROP TABLE IF EXISTS "BusinessClosingHours";
DROP TABLE IF EXISTS "BusinessOpeningHours";
DROP TABLE IF EXISTS "BusinessPhones";
DROP TABLE IF EXISTS "BusinessRatings";
DROP TABLE IF EXISTS "BusinessSocialMedia";
DROP TABLE IF EXISTS "BusinessSources";
DROP TABLE IF EXISTS "Countries";
DROP TABLE IF EXISTS "States";
DROP TABLE IF EXISTS "Cities";
DROP TABLE IF EXISTS "PostalCodes";
DROP TABLE IF EXISTS "SequelizeMeta";
DROP TABLE IF EXISTS "Timezones";
DROP TABLE IF EXISTS "Queues";