FROM nginx:latest AS nginx

# WORKDIR /app

# RUN apt-get update && apt-get install -y gettext-base
# # RUN rm /etc/nginx/conf.d/nginx.conf

# COPY nginx/conf.d/nginx.conf /etc/nginx/conf.d/

# EXPOSE 80 443
# CMD ["nginx", "-g", "daemon off;"]
