- name: Delete Istio configuration
  command: kubectl delete -f kubernetes/istio/{{ ENVIRONMENT }}/
  args:
    chdir: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/
  environment:
    KUBECONFIG: "/home/{{ USER }}/.kube/config"

- name: Delete Kubernetes manifests from all microservices
  command: kubectl delete -f kubernetes/k8s/{{ item }}/{{ ENVIRONMENT }}/
  args:
    chdir: /home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}/
  environment:
    KUBECONFIG: "/home/{{ USER }}/.kube/config"
  loop:
    - main
    - auth
    - countries
    - businesses
    - queues
    - users
