# roles/chocolatey/tasks/main.yml

---
# Main entry point for chocolatey role

- name: Ensure Chocolatey is installed
  win_shell: |
    Set-ExecutionPolicy Bypass -Scope Process -Force
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  args:
    creates: C:\ProgramData\chocolatey\bin\choco.exe

- name: Install requested packages via Chocolatey
  include_tasks: install_packages.yml
