services:
  dev8x-prod:
    container_name: dev8x-prod
    image: dev8x-prod:latest
    build:
      context: ../../
      dockerfile: microfrontend/dev8x/Dockerfile
      target: production
    env_file:
      - ./.env.production
    ports:
      - '3003:3003'

  dev8x-stag:
    container_name: dev8x-stag
    image: dev8x-stag:latest
    build:
      context: ../../
      dockerfile: microfrontend/dev8x/Dockerfile
      target: production
    env_file:
      - ./.env.staging
    ports:
      - '3004:3004'

  dev8x-dev:
    container_name: dev8x-dev
    image: dev8x-dev:latest
    build:
      context: ../../
      dockerfile: microfrontend/dev8x/Dockerfile
      target: base
    env_file:
      - ./.env.development
    ports:
      - '3005:3005'

  dev8x-loc:
    container_name: dev8x-loc
    image: dev8x-loc:latest
    build:
      context: ../../
      dockerfile: microfrontend/dev8x/Dockerfile
      target: local
    env_file:
      - ./.env.local
    ports:
      - '3005:3005'
