apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users  # helps uniquely match during patch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: users-dev:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50017
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"