apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
stringData:
  DB_HOST: users-db
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: mysecretpassword
  POSTGRES_HOST: users-db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
