---
- name: Install IIS Windows feature
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes

- name: Ensure IIS service is running
  win_service:
    name: W3SVC
    state: started
    start_mode: automatic
