services:
  auth_prod:
    container_name: auth_prod
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/auth/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50003:50003'
    depends_on:
      postgres_auth_prod:
        condition: service_started
    volumes:
      - ./logs/:/microservices/auth/logs/
    networks:
      - custom_network

  auth_stag:
    container_name: auth_stag
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/auth/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50004:50004'
    depends_on:
      postgres_auth_stag:
        condition: service_started
    volumes:
      - ./logs/:/microservices/auth/logs/
    networks:
      - custom_network

  auth_dev:
    container_name: auth_dev
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/auth/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50005:50005'
    volumes:
      - ./logs/:/microservices/auth/logs/
    networks:
      - custom_network
