services:
  auth-prod:
    container_name: auth-prod
    image: auth-prod
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50003:50003'

  auth-stag:
    container_name: auth-stag
    image: auth-stag
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50004:50004'

  auth-dev:
    container_name: auth-dev
    image: auth-dev
    build:
      context: ../../
      dockerfile: microservices/auth/Dockerfile
      target: builder
    env_file:
      - ./.env
    ports:
      - '50005:50005'
