services:
  queues-prod:
    container_name: queues-prod
    image: queues-prod:latest
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50012:50012'

  queues-stag:
    container_name: queues-stag
    image: queues-stag:latest
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50013:50013'

  queues-dev:
    container_name: queues-dev
    image: queues-dev:latest
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
      target: builder
    env_file:
      - ./.env
    ports:
      - '50014:50014'
