services:
  queues_prod:
    container_name: queues_prod
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/queues/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50013:50013'
    depends_on:
      postgres_queues_prod:
        condition: service_started
    volumes:
      - ./logs/:/microservices/queues/logs/
    networks:
      - custom_network

  queues_stag:
    container_name: queues_stag
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/queues/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50014:50013'
    depends_on:
      postgres_queues_stag:
        condition: service_started
    volumes:
      - ./logs/:/microservices/queues/logs/
    networks:
      - custom_network

  queues_dev:
    container_name: queues_dev
    build:
      context: ../../
      dockerfile: microservices/queues/Dockerfile
      target: development
    entrypoint: ['/bin/bash', '/app/microservices/queues/entrypoint.sh']
    env_file:
      - ./.env
    ports:
      - '50015:50013'
    depends_on:
      postgres_queues_dev:
        condition: service_started
    volumes:
      - ./logs/:/microservices/queues/logs/
    networks:
      - custom_network
