apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth  # helps uniquely match during patch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-dev:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50005
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2"
              memory: "2Gi"