apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  host: auth-db
  port: "5432"
  dbname: postgres
  username: postgres
  password: mysecretpassword
  DB_HOST: auth-db
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  DB_PASSWORD: mysecretpassword
  POSTGRES_HOST: auth-db
  POSTGRES_PORT: "5432"
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: mysecretpassword
