---
- name: Create registry data directory
  file:
    path: /opt/registry/data
    state: directory
    mode: '0755'

- name: Create registry config directory
  file:
    path: /opt/registry/config
    state: directory
    mode: '0755'

- name: Create Docker registry config file with deletion enabled
  copy:
    dest: /opt/registry/config/config.yml
    content: |
      version: 0.1
      storage:
        filesystem:
          rootdirectory: /var/lib/registry
      delete:
        enabled: true
      http:
        addr: :5000
    owner: root
    group: root
    mode: '0644'

- name: Check if registry container already exists
  shell: docker ps -a --format '{{"{{"}}.Names{{"}}"}}' | grep -w registry
  register: registry_exists
  failed_when: false
  changed_when: false
  become: false

- name: Run Docker registry container using docker CLI (only if not running)
  shell: |
    docker run -d \
      -p 5000:5000 \
      --restart=always \
      --network=host \
      --name registry \
      -v /opt/registry/config/config.yml:/etc/docker/registry/config.yml \
      -v /opt/registry/data:/var/lib/registry \
      registry:2
  when: registry_exists.rc != 0
  become: true

- name: Ensure Docker is configured for insecure registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries" : ["{{ docker_registry_ip }}"]
      }
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker

- name: Allow port 5000 through UFW (if UFW is enabled)
  ufw:
    rule: allow
    port: 5000
    proto: tcp
  when: ansible_facts.packages.ufw is defined
