---
- name: Provision Windows Scraper Server
  hosts: windows
  vars:
    env: scraper
  roles:
    - role: common
    - role: chocolatey
    - role: python
    - role: scraper
    - role: windows_firewall
