---
- name: Create website folder
  win_file:
    path: "C:\\inetpub\\wwwroot\\{{ site_name }}"
    state: directory

- name: Copy website files to server
  win_copy:
    src: "{{ local_site_path }}\\"
    dest: "C:\\inetpub\\wwwroot\\{{ site_name }}"
    recurse: yes

- name: Remove default IIS website
  win_iis_website:
    name: 'Default Web Site'
    state: absent

- name: Create new IIS website
  win_iis_website:
    name: "{{ site_name }}"
    state: started
    physical_path: "C:\\inetpub\\wwwroot\\{{ site_name }}"
    port: "{{ site_port }}"
    ip: '*'
    hostname: "{{ site_hostname | default(omit) }}"
