services:
  troophunter_prod:
    container_name: troophunter_prod
    build:
      context: ../../
      dockerfile: microfrontend/troophunter-landing/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    depends_on:
      - main_prod
    networks:
      - custom_network

  troophunter_stag:
    container_name: troophunter_stag
    build:
      context: ../../
      dockerfile: microfrontend/troophunter-landing/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    depends_on:
      - main_stag
    networks:
      - custom_network

  troophunter_dev:
    container_name: troophunter_dev
    build:
      context: ../../
      dockerfile: microfrontend/troophunter-landing/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '3002:3002'
    depends_on:
      - main_dev
    networks:
      - custom_network
