---
- hosts: ubuntu
  # user: ubuntu-server
  become: true
  become_method: sudo
  become_user: root
  vars_files:
    - /ansible/linux/secrets/github_token
  vars:
    USER: ubuntu-server
    ansible_user: ubuntu-server
    NODE_VERSION: 20.12.2
    GIT_REPO: "https://{{ github_token }}@github.com/helloabdul/TroopHunterNew.git"
    GIT_BRANCH: develop
    PROJECT_NAME: TroopHunter
    ENVIRONMENT: dev
    ENV_PATH: "/workspace/ansible/linux/secrets"
    SERVER_IP: "192.168.1.200"
    script_local_path: ./install-kubeadm.sh  # Adjust this to your actual script path
    script_remote_path: /tmp/install-kubeadm.sh
    # PROTONVPN_USERNAME: alrazzaq1971@gmail.com
    # PROTONVPN_PASSWORD: 7!>G^dmkmwwWbc50
    # PROTONVPN_SERVER: US-NY#627
  gather_facts: true
  roles:
    # - proton
    - common
    - nvm
    # - node
    - docker
    - kubectl
    - minikube
    - istioctl
    - github
    - docker_deployment
    - local_deployment