---
- name: Clone a private repository into {{PROJECT_NAME}} folder.
  git:
    repo: "{{ GIT_REPO }}"
    version: "{{ GIT_BRANCH }}"
    dest: "/home/{{ USER }}/{{ PROJECT_NAME }}/{{ ENVIRONMENT }}"
    accept_hostkey: yes
    clone: true
  become: false
