services:
  users-prod:
    container_name: users-prod
    image: users-prod:latest
    build:
      context: ../../
      dockerfile: microservices/users/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50015:50015'

  users-stag:
    container_name: users-stag
    image: users-stag:latest
    build:
      context: ../../
      dockerfile: microservices/users/Dockerfile
    env_file:
      - ./.env
    ports:
      - '50016:50016'

  users-dev:
    container_name: users-dev
    image: users-dev:latest
    build:
      context: ../../
      dockerfile: microservices/users/Dockerfile
      target: builder
    env_file:
      - ./.env
