services:
  main-prod:
    container_name: main-prod
    image: main-prod:latest
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '50000:50000'

  main-stag:
    container_name: main-stag
    image: main-stag
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '50001:50001'

  main-dev:
    container_name: main-dev
    image: main-dev
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: development
    env_file:
      - ./.env
    ports:
      - '50002:50002'
