services:
  main-prod:
    container_name: main-prod
    image: main-prod:latest
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: production
    env_file:
      - ./.env.production
    environment:
      - NODE_ENV=production
    ports:
      - '50000:50000'

  main-stag:
    container_name: main-stag
    image: main-stag:latest
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: builder
    env_file:
      - ./.env.staging
    environment:
      - NODE_ENV=staging
    ports:
      - '50001:50001'

  main-dev:
    container_name: main-dev
    image: main-dev:latest
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: builder
    env_file:
      - ./.env.development
    environment:
      - NODE_ENV=development
    ports:
      - '50002:50002'

  main-loc:
    container_name: main-loc
    image: main-loc:latest
    build:
      context: ../../
      dockerfile: microservices/main/Dockerfile
      target: local
    env_file:
      - ./.env.local
    environment:
      - NODE_ENV=local
    ports:
      - '50002:50002'
    volumes:
      - ../../microservices/main:/app/microservices/main
      - /app/microservices/main/node_modules
    command: ['npm', 'run', 'local']
